In [1]:
import polars as pl

In [2]:
data_idx = pl.read_parquet('../downstream_idx.parquet')

In [3]:
data_idx

shape: (61_175, 54)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ hadm_id  ┆ hosp_admi ┆ hosp_disc ┆ … ┆ wStay_sta ┆ wStay_end ┆ wStay_sta ┆ wStay_end │
│ d         ┆ ---      ┆ ssion_tim ┆ harge_tim ┆   ┆ rt_1024   ┆ _1024     ┆ rt_1536   ┆ _1536     │
│ ---       ┆ i64      ┆ e         ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
│           ┆          ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10000690  ┆ 25860671 ┆ 2150-11-0 ┆ 2150-11-1 ┆ … ┆ 3765      ┆ 4788      ┆ 3253      ┆ 4788      │
│           ┆          ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 18:02:00  ┆ 13:45:00  ┆   ┆           ┆           ┆           ┆           │
│ 10001217  ┆ 24597018 ┆ 2157-11-1 ┆ 2157-11-2 ┆ … ┆ 550       ┆ 1573      ┆ 127       ┆ 1573      │
│           ┆          ┆ 8         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 22:56:00  ┆ 18:00:00  ┆   ┆           ┆           ┆           ┆           │
│ 10001725  ┆ 25563031 ┆ 2110-04-1 ┆ 2110-04-1 ┆ … ┆ 219       ┆ 1242      ┆ 29        ┆ 1242      │
│           ┆          ┆ 1         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 15:08:00  ┆ 15:00:00  ┆   ┆           ┆           ┆           ┆           │
│ 10001884  ┆ 26184834 ┆ 2131-01-0 ┆ 2131-01-2 ┆ … ┆ 17536     ┆ 18559     ┆ 17024     ┆ 18559     │
│           ┆          ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 20:39:00  ┆ 05:15:00  ┆   ┆           ┆           ┆           ┆           │
│ 10002013  ┆ 23581541 ┆ 2160-05-1 ┆ 2160-05-2 ┆ … ┆ 1811      ┆ 2834      ┆ 1299      ┆ 2834      │
│           ┆          ┆ 8         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 07:45:00  ┆ 13:30:00  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 19999297  ┆ 21439025 ┆ 2162-08-1 ┆ 2162-08-2 ┆ … ┆ 9364      ┆ 10387     ┆ 8852      ┆ 10387     │
│           ┆          ┆ 4         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 23:55:00  ┆ 04:16:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999442  ┆ 26785317 ┆ 2148-11-1 ┆ 2148-12-0 ┆ … ┆ 6428      ┆ 7451      ┆ 5916      ┆ 7451      │
│           ┆          ┆ 9         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 10:00:00  ┆ 16:25:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999828  ┆ 25744818 ┆ 2149-01-0 ┆ 2149-01-1 ┆ … ┆ 1489      ┆ 2512      ┆ 977       ┆ 2512      │
│           ┆          ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 16:44:00  ┆ 17:00:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999840  ┆ 21033226 ┆ 2164-09-1 ┆ 2164-09-1 ┆ … ┆ 7139      ┆ 8162      ┆ 6627      ┆ 8162      │
│           ┆          ┆ 0         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 13:47:00  ┆ 13:42:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999987  ┆ 23865745 ┆ 2145-11-0 ┆ 2145-11-1 ┆ … ┆ 2037      ┆ 3060      ┆ 1525      ┆ 3060      │
│           ┆          ┆ 2         ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 21:38:00  ┆ 12:57:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
task = 'y_mort'
# positive 
data_idx.filter(pl.col(task) == 1)

shape: (6_276, 54)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ hadm_id  ┆ hosp_admi ┆ hosp_disc ┆ … ┆ wStay_sta ┆ wStay_end ┆ wStay_sta ┆ wStay_end │
│ d         ┆ ---      ┆ ssion_tim ┆ harge_tim ┆   ┆ rt_1024   ┆ _1024     ┆ rt_1536   ┆ _1536     │
│ ---       ┆ i64      ┆ e         ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
│           ┆          ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10001884  ┆ 26184834 ┆ 2131-01-0 ┆ 2131-01-2 ┆ … ┆ 17536     ┆ 18559     ┆ 17024     ┆ 18559     │
│           ┆          ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 20:39:00  ┆ 05:15:00  ┆   ┆           ┆           ┆           ┆           │
│ 10003637  ┆ 28317408 ┆ 2150-05-1 ┆ 2150-05-2 ┆ … ┆ 11639     ┆ 12662     ┆ 11127     ┆ 12662     │
│           ┆          ┆ 4         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 19:51:00  ┆ 16:25:00  ┆   ┆           ┆           ┆           ┆           │
│ 10004401  ┆ 25777141 ┆ 2144-06-0 ┆ 2144-06-1 ┆ … ┆ 83552     ┆ 84575     ┆ 83040     ┆ 84575     │
│           ┆          ┆ 5         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 19:45:00  ┆ 21:30:00  ┆   ┆           ┆           ┆           ┆           │
│ 10004720  ┆ 22081550 ┆ 2186-11-1 ┆ 2186-11-1 ┆ … ┆ 8257      ┆ 9280      ┆ 7745      ┆ 9280      │
│           ┆          ┆ 2         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 18:01:00  ┆ 18:30:00  ┆   ┆           ┆           ┆           ┆           │
│ 10005817  ┆ 28661809 ┆ 2135-01-0 ┆ 2135-01-1 ┆ … ┆ 27864     ┆ 28887     ┆ 27352     ┆ 28887     │
│           ┆          ┆ 3         ┆ 9         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 21:54:00  ┆ 18:36:00  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 19993954  ┆ 21675305 ┆ 2142-03-2 ┆ 2142-03-2 ┆ … ┆ 1132      ┆ 2155      ┆ 620       ┆ 2155      │
│           ┆          ┆ 7         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 10:57:00  ┆ 09:31:00  ┆   ┆           ┆           ┆           ┆           │
│ 19995127  ┆ 27369164 ┆ 2138-06-0 ┆ 2138-06-1 ┆ … ┆ 3728      ┆ 4751      ┆ 3216      ┆ 4751      │
│           ┆          ┆ 6         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 18:00:00  ┆ 01:48:00  ┆   ┆           ┆           ┆           ┆           │
│ 19998843  ┆ 24842066 ┆ 2187-02-0 ┆ 2187-02-0 ┆ … ┆ 4493      ┆ 5516      ┆ 3981      ┆ 5516      │
│           ┆          ┆ 5         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 09:27:00  ┆ 17:28:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999297  ┆ 21439025 ┆ 2162-08-1 ┆ 2162-08-2 ┆ … ┆ 9364      ┆ 10387     ┆ 8852      ┆ 10387     │
│           ┆          ┆ 4         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 23:55:00  ┆ 04:16:00  ┆   ┆           ┆           ┆           ┆           │
│ 19999840  ┆ 21033226 ┆ 2164-09-1 ┆ 2164-09-1 ┆ … ┆ 7139      ┆ 8162      ┆ 6627      ┆ 8162      │
│           ┆          ┆ 0         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 13:47:00  ┆ 13:42:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [43]:

import os
import json
import torch
import bisect
import chromadb
import numpy as np
import polars as pl

from torch import nn

from math import ceil
from pathlib import Path
from collections import defaultdict
from datasets import load_from_disk
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split
from typing import Dict, Iterable, List, Optional, Any, Union, Literal, Tuple, Callable

class Tokenizer:
    def __init__(
        self,
        codes_parquet_fp: str,
        special_tokens: Optional[Iterable[str]] = None,
        force_special_ids: bool = True,  # pin [PAD]=0 etc.
    ):
        if special_tokens is None:
            special_tokens = ["[PAD]", "[MASK]", "[CLS]", "[UNK]"]


        df_codes = pl.read_parquet(str(codes_parquet_fp), columns=["code"])
        base_codes = df_codes.get_column("code").to_list()
        seen = set()
        unique_codes = []
        for c in base_codes:
            if c not in seen:
                unique_codes.append(c)
                seen.add(c)

        vocab_list: List[str] = []
        special_tokens = list(special_tokens)

        if force_special_ids:
            for tok in ["[PAD]", "[MASK]", "[CLS]", "[UNK]"]:
                if tok in special_tokens and tok not in seen:
                    vocab_list.append(tok)
                    seen.add(tok)
                elif tok in special_tokens and tok in seen:

                    vocab_list.append(tok)
            for tok in special_tokens:
                if tok not in seen:
                    vocab_list.append(tok)
                    seen.add(tok)
        else:
            for tok in special_tokens:
                if tok not in seen:
                    vocab_list.append(tok)
                    seen.add(tok)


        vocab_list.extend(unique_codes)


        self.id2code: List[str] = vocab_list
        self.code2id: Dict[str, int] = {tok: idx for idx, tok in enumerate(vocab_list)}
        self.vocab_size: int = len(self.id2code)

        self.pad_token  = "[PAD]" if "[PAD]" in self.code2id else None
        self.mask_token = "[MASK]" if "[MASK]" in self.code2id else None
        self.cls_token  = "[CLS]" if "[CLS]" in self.code2id else None
        self.unk_token  = "[UNK]" if "[UNK]" in self.code2id else None

        self.pad_id  = self.code2id[self.pad_token]  if self.pad_token  else 0
        self.mask_id = self.code2id[self.mask_token] if self.mask_token else None
        self.cls_id  = self.code2id[self.cls_token]  if self.cls_token  else None
        self.unk_id  = self.code2id[self.unk_token]  if self.unk_token  else None


        type_set = set()
        for tok in self.id2code:
            prefix = tok.split("//", 1)[0]
            type_set.add(prefix)

        types_sorted = sorted(t for t in type_set if t not in ("[PAD]",))
        self.type2id: Dict[str, int] = {"[PAD]": 0}
        next_id = 1
        for sp in ["[MASK]", "[CLS]", "[UNK]"]:
            if sp in type_set:
                self.type2id[sp] = next_id; next_id += 1
        for t in types_sorted:
            if t not in self.type2id:
                self.type2id[t] = next_id
                next_id += 1

        self._code2id_df = pl.DataFrame({"code": self.id2code,
                                         "input_id": list(range(self.vocab_size))}) \
                               .with_columns(pl.col("code").cast(pl.Categorical))
        self._type2id_df = pl.DataFrame({"code_type": list(self.type2id.keys()),
                                         "type_id":   list(self.type2id.values())}) \
                               .with_columns(pl.col("code_type").cast(pl.Categorical))


    def encode(self, codes: Iterable[str]) -> List[int]:
        get = self.code2id.get
        if self.unk_id is not None:
            fallback = self.unk_id
        else:
            fallback = self.pad_id if self.pad_id is not None else 0
        return [get(c, fallback) for c in codes]

    def decode(self, ids: Iterable[int]) -> List[str]:
        out = []
        for i in ids:
            if 0 <= i < self.vocab_size:
                out.append(self.id2code[i])
            else:
                out.append(self.unk_token or "[UNK]")
        return out

    def save(self, path: str) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        obj = {
            "id2code": self.id2code,
            "special_tokens": [t for t in ["[PAD]", "[MASK]", "[CLS]", "[UNK]"] if t in self.code2id],
            "type2id": self.type2id,
            "pad_id": self.pad_id,
            "mask_id": self.mask_id,
            "cls_id": self.cls_id,
            "unk_id": self.unk_id,
        }
        with open(path, "w") as f:
            json.dump(obj, f, indent=2)

    @classmethod
    def load(cls, path: str) -> "Tokenizer":
        path = Path(path)
        with open(path) as f:
            obj = json.load(f)

        tok = cls.__new__(cls) 

        tok.id2code = obj["id2code"]
        tok.code2id = {tok_: i for i, tok_ in enumerate(tok.id2code)}
        tok.vocab_size = len(tok.id2code)

        tok.special_tokens = obj.get("special_tokens", [])
        tok.type2id = obj.get("type2id", {})

        tok.pad_token  = "[PAD]" if "[PAD]" in tok.code2id else None
        tok.mask_token = "[MASK]" if "[MASK]" in tok.code2id else None
        tok.cls_token  = "[CLS]" if "[CLS]" in tok.code2id else None
        tok.unk_token  = "[UNK]" if "[UNK]" in tok.code2id else None

        tok.pad_id  = obj.get("pad_id", tok.code2id.get("[PAD]", 0))
        tok.mask_id = obj.get("mask_id", tok.code2id.get("[MASK]")) if "[MASK]" in tok.code2id else None
        tok.cls_id  = obj.get("cls_id", tok.code2id.get("[CLS]"))   if "[CLS]" in tok.code2id else None
        tok.unk_id  = obj.get("unk_id", tok.code2id.get("[UNK]"))   if "[UNK]" in tok.code2id else None

        # Rebuild Polars lookup frames
        tok._code2id_df = pl.DataFrame({"code": tok.id2code,
                                        "input_id": list(range(tok.vocab_size))}) \
                              .with_columns(pl.col("code").cast(pl.Categorical))
        tok._type2id_df = pl.DataFrame({"code_type": list(tok.type2id.keys()),
                                        "type_id":   list(tok.type2id.values())}) \
                              .with_columns(pl.col("code_type").cast(pl.Categorical))
        return tok

    @property
    def code2id_df(self) -> pl.DataFrame:
        return self._code2id_df

    @property
    def type2id_df(self) -> pl.DataFrame:
        return self._type2id_df
    





class SequencesGenerator:
    def __init__(
        self,
        tokenizer_path: str,
        chunk_length: int = 1024,
        overlap: int = 128,
        return_numeric: bool = False,
        return_text: bool = False,
        return_time: bool = False,
        return_ids: bool = False,
    ):

        self.tokenizer = Tokenizer.load(tokenizer_path)
        self.chunk_length = chunk_length
        self.overlap = overlap
        self.return_numeric = return_numeric
        self.return_text = return_text
        self.return_time = return_time
        self.return_ids = return_ids

    def encode_sequence(
        self,
        timeline: pl.DataFrame,
        max_length: Optional[int] = None,
        pad_to_max: bool = False,
        truncation: Literal["head", "tail"] = "tail",
        add_cls: bool = False,
    ) -> Dict[str, Union[List[int], List[float], List[str]]]:
        """
        Vectorized build of:
          input_ids, attention_mask, visit_ids, stage_ids, type_ids
          + optional numeric/text streams (+ masks)
        """
        df = timeline
        
        if "seq_id" in df.columns:

            uniq = df.select(pl.col("seq_id")).unique(maintain_order=True)
            uniq = uniq.with_row_count(name="visit_ids_raw")  # 0..K-1
            df = df.join(uniq, on="seq_id", how="left").with_columns(
                (pl.col("visit_ids_raw") ).alias("visit_id").fill_null(0)
            ).drop("visit_ids_raw")
        else:
            df = df.with_columns(pl.lit(0).alias("visit_id"))

        stage_cols = ["out_id", "er_id", "hadm_id", "icustay_id"]
        present_stages = [c for c in stage_cols if c in df.columns]
        if present_stages:

            expr = pl.lit(0)
            for i, col in enumerate(present_stages, start=1):
                expr = pl.when(expr.eq(0) & pl.col(col).is_not_null()).then(i).otherwise(expr)
            df = df.with_columns(expr.alias("stage_id"))
        else:
            df = df.with_columns(pl.lit(0).alias("stage_id"))

        df = df.join(
            self.tokenizer.type2id_df,
            on=pl.col("code_type").cast(pl.Categorical),
            how="left",
        ).with_columns(pl.col("type_id").fill_null(0))

        df = df.join(
            self.tokenizer.code2id_df,
            on=pl.col("code").cast(pl.Categorical),
            how="left",
        )


        unk_id = self.tokenizer.unk_id if self.tokenizer.unk_id is not None else self.tokenizer.pad_id or 0
        df = df.with_columns(pl.col("input_id").fill_null(unk_id))

        df = df.with_columns(
            pl.when(pl.col("code").str.starts_with("TIME-GAP//"))
              .then(0)
              .otherwise(pl.col("visit_id"))
              .alias("visit_id"),
            pl.when(pl.col("code").str.starts_with("TIME-GAP//"))
              .then(0)
              .otherwise(pl.col("stage_id"))
              .alias("stage_id"),
        )


        if add_cls and (self.tokenizer.cls_token is not None):
            cls_row = {
                "code": self.tokenizer.cls_token,
                "code_type": "[CLS]",
                "visit_id": 0,
                "stage_id": 0,
                "type_id": self.tokenizer.type2id.get("[CLS]", 0),
                "input_id": self.tokenizer.cls_id,
            }

            if self.return_numeric:
                cls_row["numeric_value"] = None
            if self.return_text:
                cls_row["text_value"] = None

            df = pl.concat([pl.DataFrame([cls_row]), df], how="vertical_relaxed")


        input_ids = df.get_column("input_id").cast(pl.Int64).to_list()
        type_ids = df.get_column("type_id").cast(pl.Int64).to_list()
        visit_ids = df.get_column("visit_id").cast(pl.Int64).to_list()
        stage_ids = df.get_column("stage_id").cast(pl.Int64).to_list()
        attention_mask = [1] * len(input_ids)


        value_payload = self._build_value_streams(
            df=df,
            max_length=max_length,
            pad_to_max=pad_to_max,
            truncation=truncation,
        )

        # --- truncate/pad core streams in one go ---
        input_ids      = self._truncate(input_ids,      max_length, truncation)
        type_ids       = self._truncate(type_ids,       max_length, truncation)
        visit_ids      = self._truncate(visit_ids,      max_length, truncation)
        stage_ids      = self._truncate(stage_ids,      max_length, truncation)
        attention_mask = [1] * len(input_ids)

        if pad_to_max and max_length is not None and len(input_ids) < max_length:
            pad_len = max_length - len(input_ids)
            pad_id = self.tokenizer.pad_id if self.tokenizer.pad_id is not None else 0
            input_ids      = input_ids + [pad_id] * pad_len
            type_ids       = type_ids + [0] * pad_len
            visit_ids      = visit_ids + [0] * pad_len
            stage_ids      = stage_ids + [0] * pad_len
            attention_mask = attention_mask + [0] * pad_len

        out = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "visit_ids": visit_ids,
            "stage_ids": stage_ids,
            "type_ids": type_ids,
        }
        out.update(value_payload)
        return out

    def get_overlapped_chunks(
        self,
        timeline: Dict[str, Iterable],
        chunk_length: Optional[int] = None,
        overlap: Optional[int] = None,
        add_cls_per_chunk: bool = True,
    ) -> List[Dict[str, List[Any]]]:
        """
        Sliding-window chunking with optional [CLS] per chunk and padding.
        """
        if chunk_length is None or overlap is None:
            chunk_length = self.chunk_length
            overlap = self.overlap

        fields = ["input_ids", "attention_mask", "visit_ids", "stage_ids", "type_ids"]
        for extra in ("numeric_values", "numeric_mask", "text_values", "text_mask", 'time_diff'):
            if extra in timeline and extra not in fields:
                fields.append(extra)

        n = len(timeline["input_ids"])
        payload = chunk_length - (1 if add_cls_per_chunk else 0)
        step = max(1, payload - overlap)

        num_chunks = 1 if n <= payload else ceil((n - payload) / step) + 1
        starts = [i * step for i in range(num_chunks)]

        cls_defaults = {
            "input_ids": self.tokenizer.cls_id if self.tokenizer.cls_id is not None else (self.tokenizer.pad_id or 0),
            "attention_mask": 1,
            "visit_ids": 0,
            "stage_ids": 0,
            "type_ids": self.tokenizer.type2id.get("[CLS]", 0),
            "numeric_values": 0.0,
            "numeric_mask": 0,
            "text_values": "",
            "text_mask": 0,
            "time_diff":0.0}

        chunks = []
        for start in starts:
            end = min(n, start + payload)
            sliced = {k: list(timeline[k][start:end]) for k in fields if k in timeline}

            if "attention_mask" in sliced:
                sliced["attention_mask"] = [1] * len(sliced["input_ids"])

            if add_cls_per_chunk:
                for k in list(sliced.keys()):
                    sliced[k] = [cls_defaults[k]] + sliced[k]

            cur_len = len(sliced["input_ids"])
            if cur_len < chunk_length:
                pad_len = chunk_length - cur_len
                for k in list(sliced.keys()):
                    sliced[k] = self._pad_list(sliced[k], pad_len, 0)

            chunks.append(sliced)
        return chunks


    def _build_value_streams(
        self,
        df: pl.DataFrame,
        max_length: Optional[int],
        pad_to_max: bool,
        truncation: Literal["head", "tail"],
    ) -> Dict[str, List[Any]]:
        out: Dict[str, List[Any]] = {}
        # Numeric stream
        if self.return_numeric:
            if "numeric_value" in df.columns:
                vals = df.get_column("numeric_value").to_list()
            else:
                vals = [None] * df.height
            num_mask = [1 if (v is not None) else 0 for v in vals]
            vals = [0.0 if v is None else float(v) for v in vals]

            vals = self._truncate(vals, max_length, truncation)
            num_mask = self._truncate(num_mask, max_length, truncation)

            if pad_to_max and max_length is not None and len(vals) < max_length:
                pad_len = max_length - len(vals)
                vals += [0.0] * pad_len
                num_mask += [0] * pad_len

            out["numeric_values"] = vals
            out["numeric_mask"] = num_mask

        # Text stream
        if self.return_text:
            if "text_value" in df.columns:
                txt = df.get_column("text_value").to_list()
            else:
                txt = [None] * df.height
            txt = [("" if (t is None or str(t) == "___") else str(t)) for t in txt]
            txt_mask = [1 if (t != "") else 0 for t in txt]

            txt = self._truncate(txt, max_length, truncation)
            txt_mask = self._truncate(txt_mask, max_length, truncation)

            if pad_to_max and max_length is not None and len(txt) < max_length:
                pad_len = max_length - len(txt)
                txt += [""] * pad_len
                txt_mask += [0] * pad_len

            out["text_values"] = txt
            out["text_mask"] = txt_mask

            
        if self.return_time:
            if "time_diff" in df.columns:
                df = df.with_columns(pl.col(['time_diff'])).fill_null(0.0)
                time_diff = df.get_column("time_diff").to_list()
                time_diff = self._scale_time_deltas(time_diff)
                time_stamp = df.get_column("time").to_list()
            else:
                time_diff = [None] * df.height
                time_stamp = [None] * df.height


            if pad_to_max and max_length is not None and len(time_diff) < max_length:
                pad_len = max_length - len(time_diff)
                time_diff += [0] * pad_len
                time_stamp += [0] * pad_len


            out["time_diff"] = time_diff
            out["time_stamp"] = time_stamp
            
        if self.return_ids:
            if "seq_id" in df.columns:
                
                seq_id = df.get_column("seq_id").cast(pl.Int32).to_list()
                out_id = df.get_column("out_id").cast(pl.Int32).to_list()
                er_id =  df.get_column("er_id").cast(pl.Int32).to_list()
                hadm_id = df.get_column("hadm_id").cast(pl.Int32).to_list()
                icustay_id = df.get_column("hadm_id").cast(pl.Int32).to_list()
            else:
                seq_id = [None] * df.height
                out_id = [None] * df.height
                er_id =  [None] * df.height
                hadm_id = [None] * df.height
                icustay_id = [None] * df.height

            if pad_to_max and max_length is not None and len(time_diff) < max_length:
                pad_len = max_length - len(time_diff)
                seq_id += [0] * pad_len
                out_id += [0] * pad_len
                er_id += [0] * pad_len
                hadm_id += [0] * pad_len
                icustay_id += [0] * pad_len

            out["seq_id"] = seq_id
            out["out_id"] = out_id
            out["er_id"] = er_id
            out["hadm_id"] = hadm_id
            out["icustay_id"] = icustay_id

        return out
    
    def _scale_time_deltas(self, deltas_list):
        deltas = np.asarray(deltas_list, dtype=float)
        compressed = np.log1p(deltas)              
        scaled = compressed / np.log(5328.93125)         
        return scaled.tolist()

    @staticmethod
    def _truncate(seq: List[Any], max_length: Optional[int], truncation: str) -> List[Any]:
        if max_length is None or len(seq) <= max_length:
            return seq
        return seq[-max_length:] if truncation == "head" else seq[:max_length]

    @staticmethod
    def _pad_list(lst: List[Any], pad_len: int, pad_value: Any) -> List[Any]:
        if pad_len <= 0:
            return lst
        return lst + [pad_value] * pad_len






class EHRPretrainDataset(Dataset):
    def __init__(self,
                 dataset_path: str,
                 data_idx_path: str,
                 seq_generator: SequencesGenerator,
                 needed_cols: list = ['subject_id', 'input_ids', 'attention_mask', 'visit_ids', 'stage_ids', 'type_ids'],
                 split: str = 'all') -> None:
        
        hf_dataset = load_from_disk(dataset_path)
        self.hf_dataset = hf_dataset.flatten_indices().select_columns(needed_cols) \
                                      .with_format("numpy", columns=needed_cols, output_all_columns=False)
        
        self.seq_generator = seq_generator
        
        sids = self.hf_dataset["subject_id"]        
        self.index = defaultdict(list)
        for i, sid in enumerate(sids):
            self.index[sid].append(i)
        
        data_idx =  pl.scan_parquet(data_idx_path).collect()
        splits = {'all': data_idx,
                  'train':data_idx.filter(pl.col('split') == 'train'),
                  'val':  data_idx.filter(pl.col('split') == 'val')}

        self.data_idx, self.cum, self.subj = self._get_chunks_count(data_idx=splits[split],
                                                                    chunk_length=self.seq_generator.chunk_length,
                                                                    overlap=self.seq_generator.overlap)
        
        
    def __len__(self) -> int:
        return self.cum[-1]


    
    def __getitem__(self,
                    idx: int):
        

        subject_id, chunk_id = self._get_chunk_at_idx(idx=idx,
                                                      cumm_sum=self.cum,
                                                      subjects=self.subj)
        

        timeline_encoded = self.hf_dataset.select(self.index[subject_id])[0]
        chunks = self.seq_generator.get_overlapped_chunks(timeline= timeline_encoded,
                                                          chunk_length= self.seq_generator.chunk_length,
                                                          overlap=self.seq_generator.overlap)
        

        return chunks[chunk_id]
    

    def _build_dataset_index(self,
                             data_path, 
                             subject_col="subject_id") -> pl.DataFrame:
        pieces = []
        for p in os.listdir(data_path):
            df = (pl.scan_parquet(os.path.join(data_path,p)).select(subject_col).collect()
                    .group_by(subject_col)
                    .len()
                    .rename({"len": "n_events"})
                 )
            df = df.with_columns(pl.lit(str(p)).alias("shard"))  # optional
            pieces.append(df)


        df = (pl.concat(pieces, how="vertical")
                  .group_by([subject_col, "shard"])
                  .agg(pl.col("n_events").sum())
                  .rename({subject_col:"subject_id"})).sort('subject_id')

        df = df.filter(pl.col('n_events') >3)

        return df
    
    
    def _read_timeline(self,
                       subject_id:int) -> pl.DataFrame:
        
        shard = self.data_idx.filter(pl.col('subject_id') == subject_id)['shard'][0]

        data = pl.scan_parquet(os.path.join(self.data_path,shard),parallel='auto').select(
                                            ['subject_id','seq_id','out_id','er_id','hadm_id', 
                                             'icustay_id','time','code','numeric_value','code_type',
                                             'text_value']).filter(
                                              pl.col('subject_id') == subject_id).collect()
        return data

    
    def _get_chunks_count(self,
                          data_idx: pl.DataFrame,
                          chunk_length: int,
                          overlap: int):
        payload  = chunk_length - 1
        step     = payload - overlap

        data_idx = data_idx.with_columns(
            pl.col("n_events")
              .map_elements(lambda n: 1 if n<=payload else ceil((n-payload)/step)+1,return_dtype=pl.Int32)
              .alias("n_chunks")
        )
        data_idx = data_idx.with_columns(
            pl.col("n_chunks").cum_sum().alias("cum_chunks")
        )

        cum  = data_idx["cum_chunks"]   
        subj = data_idx["subject_id"]
        shards = data_idx['shard']
        return data_idx, cum, subj

    def _get_chunk_at_idx(self,
                          cumm_sum: list,
                          subjects: list,
                          idx: int) -> Tuple[int,int,str]:
        i = bisect.bisect_right(cumm_sum, idx)
        left = cumm_sum[i-1] if i > 0 else 0
        return subjects[i], idx - left





    


class MLMDataCollator:
    def __init__(
        self,
        tokenizer,
        protected_tokens: List[str],
        mask_prob: float = 0.15,
        replace_prob: float = 0.80,
        random_prob: float = 0.10,
    ) -> None:

        self.tokenizer = tokenizer
        self.mask_prob = mask_prob
        self.replace_prob = replace_prob
        self.random_prob = random_prob
        self.protected_ids = self._build_protected_ids(protected_tokens)
        if tokenizer.mask_id is None:
            raise ValueError("Tokenizer must define a [MASK] token/id.")

    def __call__(self, batch: List[Union[Dict, List[Dict]]]) -> Dict[str, torch.Tensor]:
        chunks = self._flatten(batch)
        out = self._stack(chunks)
        masked_ids, labels = self._mask_batch(out["input_ids"], out["attention_mask"])
        out["input_ids"] = masked_ids
        out["labels"] = labels
        return out


    def _flatten(self, batch) -> List[Dict]:
        out: List[Dict] = []
        for item in batch:
            if isinstance(item, dict):
                out.append(item)
            elif isinstance(item, (list, tuple)):
                out.extend(item)
            else:
                raise TypeError(f"Unexpected item type: {type(item)}")
        if not out:
            raise ValueError("Empty batch after normalization.")
        return out

    def _stack(self, chunks: List[Dict]) -> Dict[str, torch.Tensor]:
        keys = list(chunks[0].keys())
        out = {}
        for k in keys:
            # Skip known non-numeric or variable-shaped fields
            if k in ("text_values",):  # add others you don't want to collate
                continue

            # Replace Nones with safe defaults
            seq_list = []
            for c in chunks:
                v = c[k]
                if isinstance(v, list):
                    v = [0 if x is None else x for x in v]  # 0 for ints/floats
                elif v is None:
                    # single value case (shouldn't happen for sequences, but guard anyway)
                    v = 0
                seq_list.append(torch.as_tensor(v))
            out[k] = torch.stack(seq_list, 0)
        return out

    def _build_protected_ids(self, protected_tokens: List[str]) -> torch.BoolTensor:

        ids = set()
        for tok in protected_tokens:
            if tok in self.tokenizer.code2id:
                ids.add(self.tokenizer.code2id[tok])
        mask = torch.zeros(self.tokenizer.vocab_size, dtype=torch.bool)
        for i in ids:
            mask[i] = True
        return mask

    def _mask_batch(
        self,
        input_ids: torch.Tensor,      
        attention_mask: torch.Tensor  
    ) -> Tuple[torch.Tensor, torch.Tensor]:

        device = input_ids.device
        prot = self.protected_ids.to(device)
        eligible = attention_mask.bool() & (~prot[input_ids])

        sample = torch.rand_like(input_ids.float()) < self.mask_prob
        to_mask = eligible & sample

        masked = input_ids.clone()
        labels = torch.full_like(input_ids, -100)
        labels[to_mask] = input_ids[to_mask]

        r = torch.rand_like(input_ids.float())
        to_mask80 = to_mask & (r < self.replace_prob)
        to_rand10 = to_mask & (r >= self.replace_prob) & (r < self.replace_prob + self.random_prob)

        # 80% -> [MASK]
        masked[to_mask80] = self.tokenizer.mask_id

        # 10% -> random allowed token
        allowed = (~prot).nonzero(as_tuple=False).squeeze(1).to(device)
        if allowed.numel() == 0:
            allowed = torch.arange(self.tokenizer.vocab_size, device=device)
        if to_rand10.any():
            rand_ids = allowed[torch.randint(0, allowed.numel(), (to_rand10.sum(),), device=device)]
            masked[to_rand10] = rand_ids
        return masked, labels
    

PROTECTED_TOKENS = [
    "[PAD]", "[CLS]", "[MASK]",
    "OUTPATIENT-START","OUTPATIENT-END",
    "EMERGENCY-START","EMERGENCY-END",
    "ADMISSION-AT-HOSPITAL","ADMISSION-AT-ICU",
    "DISCHARGE-FROM-HOSPITAL","DISCHARGE-FROM-ICU"]

limits = {
    'within24_query': {512:  ['w24_start_512',  'w24_end_512' ],
                       1024: ['w24_start_1024', 'w24_end_1024'],
                       1536: ['w24_start_1536', 'w24_end_1536'],
                       2048: ['w24_start_2048', 'w24_end_2048'],
                      },
    
    'within24_hist_icu': {512: ['wStay_min', 'w24_start_512' ],
                         1024: ['wStay_min', 'w24_start_1024'],
                         1536: ['wStay_min', 'w24_start_1536'],
                         2048: ['wStay_min', 'w24_start_2048'],
                      },
    
    'within24_hist_full': {512: [ 0, 'w24_start_512' ],
                          1024: [ 0, 'w24_start_1024'],
                          1536: [ 0, 'w24_start_1536'],
                          2048: [ 0, 'w24_start_2048'],
                          },

    
    'within48_query': {512:  ['w48_start_512',  'w48_end_512' ],
                       1024: ['w48_start_1024', 'w48_end_1024'],
                       1536: ['w48_start_1536', 'w48_end_1536'],
                       2048: ['w48_start_2048', 'w48_end_2048'],
                      },

    'within48_hist_icu': {512: ['wStay_min', 'w48_start_512' ],
                         1024: ['wStay_min', 'w48_start_1024'],
                         1536: ['wStay_min', 'w48_start_1536'],
                         2048: ['wStay_min', 'w48_start_2048'],
                      },
    
    'within48_hist_full': {512: [ 0, 'w48_start_512' ],
                          1024: [ 0, 'w48_start_1024'],
                          1536: [ 0, 'w48_start_1536'],
                          2048: [ 0, 'w48_start_2048'],
                          },
    
    'within_stay_query': {512:  ['wStay_start_512',  'wStay_end_512' ],
                          1024: ['wStay_start_1024', 'wStay_end_1024'],
                          1536: ['wStay_start_1536', 'wStay_end_1536'],
                          2048: ['wStay_start_2048', 'wStay_end_2048'],
                         },
    
    'within_stay_hist_icu': {512:  ['wStay_min', 'wStay_start_512' ],
                             1024: ['wStay_min', 'wStay_start_1024'],
                             1536: ['wStay_min', 'wStay_start_1536'],
                             2048: ['wStay_min', 'wStay_start_2048'],
                            },
    
    'within_stay_hist_full': {512:  [ 0, 'w48_start_512' ],
                              1024: [ 0, 'w48_start_1024'],
                              1536: [ 0, 'w48_start_1536'],
                              2048: [ 0, 'w48_start_2048'],
                             },
    }

class EvalDataset(Dataset):
    def __init__(self,
                 dataset_path: str,
                 data_idx_path: str,
                 seq_gen: SequencesGenerator,
                 limits_dict: dict,
                 task: str = 'y_mort',
                 main_window: str = 'within48_query', 
                 seq_length: int = 512,
                 use_time: bool = True,
                 use_numeric: bool = False,
                 add_cls=True,
                 split: str = 'train') -> None:
        
        needed_cols = ['subject_id', 'input_ids', 'attention_mask', 
                       'visit_ids', 'stage_ids', 'type_ids']

        if use_time:
            needed_cols.append('time_diff')
        if use_numeric:
            needed_cols.append('numeric_values')
            needed_cols.append('numeric_mask')
        self.start_limit = limits_dict[main_window][seq_length][0]
        self.end_limit   = limits_dict[main_window][seq_length][1]
        self.task = task
        
        self.add_cls = add_cls
        self.seq_gen = seq_gen
        self.data_idx =  pl.scan_parquet(data_idx_path).collect()
        self.data_idx =  self.data_idx.filter(pl.col('split') == split)
        
        sub_ids = set(self.data_idx.get_column("subject_id").to_list())
        hf_dataset = load_from_disk(dataset_path)

        
        hf_dataset = hf_dataset.filter(
            lambda sids: [sid in sub_ids for sid in sids],
            batched=True,
            input_columns="subject_id",
        )

        # (then continue)
        self.hf_dataset = (
            hf_dataset
            .flatten_indices()
            .select_columns(needed_cols)
            .with_format("numpy", columns=needed_cols, output_all_columns=False)
        )
        
        
        sids = self.hf_dataset["subject_id"]        
        self.index = defaultdict(list)
        for i, sid in enumerate(sids):
            self.index[sid].append(i)
        

        
    def __len__(self) -> int:
        return len(self.data_idx)


    
    def __getitem__(self,
                    idx: int):
        
        stay = self.data_idx[idx]
        subject_id = stay['subject_id'][0]
        label = stay[self.task][0]
       
        
        
        start = stay[self.start_limit][0]
        end = stay[self.end_limit][0]

        timeline_encoded = self.hf_dataset.select(self.index[subject_id])[0]
        prediction_window = {k: (v[start:end] if isinstance(v, (list, np.ndarray)) else v) for k, v in timeline_encoded.items()}
        prediction_window = self.seq_gen.get_overlapped_chunks(prediction_window, add_cls_per_chunk=self.add_cls)
        prediction_window[0]['label'] = label
        
        return prediction_window[0]


class EvalCollator:
    def __init__(self) -> None:
        pass

    def __call__(self, batch: List[Union[Dict, List[Dict]]]) -> Dict[str, torch.Tensor]:
        chunks = self._flatten(batch)
        out = self._stack(chunks)

        if "numeric_values" in out:
            vals = out["numeric_values"].float()          
            finite_mask = torch.isfinite(vals)           

            if "numeric_mask" in out:
                mask = out["numeric_mask"].bool() & finite_mask
            else:
                mask = finite_mask

            vals = torch.nan_to_num(vals, nan=0.0, posinf=0.0, neginf=0.0)

            out["numeric_values"] = vals
            out["numeric_mask"] = mask
#         if "time_diff" in out:
#             t = out["time_diff"].float()
#             t = torch.nan_to_num(t, nan=0.0, posinf=0.0, neginf=0.0)
#             out["time_diff"] = t

        return out

    def _flatten(self, batch) -> List[Dict]:
        out: List[Dict] = []
        for item in batch:
            if isinstance(item, dict):
                out.append(item)
            elif isinstance(item, (list, tuple)):
                out.extend(item)
            else:
                raise TypeError(f"Unexpected item type: {type(item)}")
        if not out:
            raise ValueError("Empty batch after normalization.")
        return out

    def _stack(self, chunks: List[Dict]) -> Dict[str, torch.Tensor]:
        keys = list(chunks[0].keys())
        out = {}
        for k in keys:

            if k in ("text_values",):  
                continue

            seq_list = []
            for c in chunks:
                v = c[k]
                if isinstance(v, list):
                    v = [0 if x is None else x for x in v]
                elif v is None:
                    v = 0
                seq_list.append(torch.as_tensor(v))
            out[k] = torch.stack(seq_list, 0)
        return out





class RetrievalEvalDataset(Dataset):
    def __init__(
        self,
        dataset_path: str,
        data_idx_path: str,
        seq_gen,
        limits_dict: dict,
        vectordb_path: str,
        embedder,
        collate_fn,
        task: str = "y_mort",
        main_window: str = "within48_query",
        seq_length: int = 512,
        top_k: int = 8,
        where_extra: Optional[dict] = None,
        use_time: bool = False,
        use_numeric: bool = False,
        add_cls: bool = True,
        split: str = "train",
    ):
        super().__init__()
        self.seq_gen = seq_gen
        self.limits_dict = limits_dict
        self.task = task
        self.main_window = main_window
        self.seq_length = seq_length
        self.top_k = top_k
        self.where_extra = where_extra or {}
        self.use_time = use_time
        self.use_numeric = use_numeric
        self.add_cls = add_cls

        self.embedder = embedder
        self.collate_fn = collate_fn

        self.start_limit = limits_dict[main_window][seq_length][0]
        self.end_limit = limits_dict[main_window][seq_length][1]

        self.data_idx = pl.scan_parquet(data_idx_path).collect()
        self.data_idx = self.data_idx.filter(pl.col("split") == split)

        needed_cols = ["subject_id", "input_ids", "attention_mask", "visit_ids", "stage_ids", "type_ids"]
        if use_time:
            needed_cols.append("time_diff")
        if use_numeric:
            needed_cols += ["numeric_values", "numeric_mask"]

        sub_ids = set(self.data_idx.get_column("subject_id").to_list())
        hf_dataset = load_from_disk(dataset_path)
        hf_dataset = hf_dataset.filter(
            lambda sids: [sid in sub_ids for sid in sids],
            batched=True,
            input_columns="subject_id",
        )

        self.hf_dataset = (
            hf_dataset.flatten_indices()
            .select_columns(needed_cols)
            .with_format("numpy", columns=needed_cols, output_all_columns=False)
        )

        sids = self.hf_dataset["subject_id"]
        self.index = defaultdict(list)
        for i, sid in enumerate(sids):
            self.index[sid].append(i)

        self.vectordb_path = vectordb_path
        self._chroma_collection_name: Optional[str] = None

        self._client = None
        self._collection = None

    def __len__(self) -> int:
        return len(self.data_idx)

    @staticmethod
    def _to_py(v):
        if isinstance(v, np.ndarray):
            return v.tolist()
        return v

    def __getstate__(self):
        state = self.__dict__.copy()
        state["_client"] = None
        state["_collection"] = None
        return state

    def _init_vectordb(self) -> None:
        if self._collection is not None:
            return

        self._client = chromadb.PersistentClient(path=self.vectordb_path)
        if self._chroma_collection_name is None:
            cols = self._client.list_collections()
            if len(cols) != 1:
                raise ValueError(
                    f"Expected 1 collection in {self.vectordb_path}, found {len(cols)}"
                )
            self._chroma_collection_name = cols[0].name

        self._collection = self._client.get_collection(name=self._chroma_collection_name)
        
        
    def _strip_query_features(self, chunk: dict) -> dict:
        drop_keys = []
        if self.use_time:
            drop_keys.append("time_diff")
        if self.use_numeric:
            drop_keys.extend(["numeric_values", "numeric_mask"])

        return {k: v for k, v in chunk.items() if k not in drop_keys}
    

        

    def _embed_query_chunk(self, query_chunk: dict) -> List[float]:
        batch = self.collate_fn([query_chunk])
        device = next(self.embedder.parameters()).device

        for k, v in list(batch.items()):
            if torch.is_tensor(v):
                batch[k] = v.to(device, non_blocking=True)

        input_ids = batch["input_ids"]
        attention_mask = batch["attention_mask"]
        type_ids = batch["type_ids"]
        visit_ids = batch["visit_ids"]
        stage_ids = batch["stage_ids"]

        time_feats = batch.get("time_diff", None) if self.use_time else None
        numeric_values = batch.get("numeric_values", None) if self.use_numeric else None
        numeric_mask = batch.get("numeric_mask", None) if self.use_numeric else None

        with torch.no_grad():
            vec = self.embedder.encode(
                input_ids=input_ids,
                attention_mask=attention_mask,
                type_ids=type_ids,
                visit_ids=visit_ids,
                stage_ids=stage_ids,
                time_feats=time_feats,
                numeric_values=numeric_values,
                numeric_mask=numeric_mask,
            ) 

        return vec[0].detach().cpu().tolist()

    def _query_vectordb(self, subject_id: int, query_chunk: dict) -> List[dict]:
        self._init_vectordb() 
        
        
        retrieval_query = self._strip_query_features(query_chunk)
        
        qvec = self._embed_query_chunk(retrieval_query)

        where = {"subject_id": int(subject_id)}
        where.update(self.where_extra)

        res = self._collection.query(
            query_embeddings=[qvec],
            n_results=self.top_k,
            where=where,
            include=["documents", "metadatas", "distances"],
        )

        docs = res.get("documents", [[]])[0]
        metas = res.get("metadatas", [[]])[0]
        dists = res.get("distances", [[]])[0]

        out = []
        for doc, meta, dist in zip(docs, metas, dists):
            ch = json.loads(doc) if isinstance(doc, str) else doc
            if self.use_time:
                ch["time_diff"] = json.loads(meta["time_diff"])
            if self.use_numeric:
                ch["numeric_values"] = json.loads(meta["numeric_values"])
                ch["numeric_mask"] = json.loads(meta["numeric_mask"])
            # ch["_retrieval_meta"] = {"distance": float(dist), "metadata": meta}
            out.append(ch)
        return out

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        stay = self.data_idx[idx]
        subject_id = int(stay["subject_id"][0])
        label = float(stay[self.task][0])

        start = stay[self.start_limit][0] if isinstance(self.start_limit, str) else int(self.start_limit)
        end = stay[self.end_limit][0] if isinstance(self.end_limit, str) else int(self.end_limit)

        timeline_encoded = self.hf_dataset.select(self.index[subject_id])[0]
        timeline_encoded = {k: self._to_py(v) for k, v in timeline_encoded.items()}

        query_window = {
            k: (v[start:end] if isinstance(v, list) else v)
            for k, v in timeline_encoded.items()
        }

        query_chunks = self.seq_gen.get_overlapped_chunks(
            query_window,
            chunk_length=self.seq_length,
            overlap=0,
            add_cls_per_chunk=self.add_cls,
        )
        query_chunk = query_chunks[0]

        history = self._query_vectordb(subject_id=subject_id, query_chunk=query_chunk)

        return {
                "query": query_chunk,
                "history": history,
                "label": label,
                "meta": {
                    "idx": int(idx),
                    "subject_id": subject_id,
                    "hadm_id": int(stay["hadm_id"][0]) if "hadm_id" in stay.columns else None,
                    "icustay_id": int(stay["icustay_id"][0]) if "icustay_id" in stay.columns else None,
                    "start": int(start),
                    "end": int(end),
                },
            }
    
class RetrievalCollator:
    def __init__(self, chunk_collator, top_k: int):
        self.chunk_collator = chunk_collator
        self.top_k = top_k

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, torch.Tensor]:
        query_chunks = [b["query"] for b in batch]
        q = self.chunk_collator(query_chunks) 

        retrieved_lists = [b["history"] for b in batch]

        for i in range(len(retrieved_lists)):
            if len(retrieved_lists[i]) == 0:
                template = query_chunks[0]
            else:
                template = retrieved_lists[i][0]  

            if len(retrieved_lists[i]) < self.top_k:
                z = {}
                for k in template.keys():
                    if isinstance(template[k], list):
                        z[k] = [0] * len(template[k])
                    else:
                        z[k] = 0
                if "input_ids" in z and isinstance(z["input_ids"], list):
                    z["input_ids"][0] = template["input_ids"][0] 
                if "attention_mask" in z and isinstance(z["attention_mask"], list):
                    z["attention_mask"][0] = 1

                # numeric_mask stays False by design
                # time / numeric values remain zero → neutral

                retrieved_lists[i] = retrieved_lists[i] + [z] * (self.top_k - len(retrieved_lists[i]))
            elif len(retrieved_lists[i]) > self.top_k:
                retrieved_lists[i] = retrieved_lists[i][:self.top_k]

        flat_retrieved = [ch for lst in retrieved_lists for ch in lst]
        r_flat = self.chunk_collator(flat_retrieved) 

        B = len(batch)
        K = self.top_k
        r = {}
        for k, v in r_flat.items():
            if v.dim() == 2:
                r[k] = v.view(B, K, v.size(-1))
            else:
                r[k] = v.view(B, K, *v.shape[1:])
        labels = torch.tensor([b["label"] for b in batch], dtype=torch.float32)
        metas = [b.get("meta", {}) for b in batch]

        return {"query": q, "history": r, "label": labels, "meta": metas}
        # return {"query": q, "history": r, "label": labels}

In [44]:


import os
import yaml
import torch
import wandb
import torch.nn as nn
import torch.distributed as dist

from typing import Callable
from transformers import BertConfig
from torchmetrics.classification import BinaryAUROC, BinaryAveragePrecision
from transformers import CONFIG_MAPPING, MODEL_FOR_MASKED_LM_MAPPING, MODEL_MAPPING, MODEL_FOR_CAUSAL_LM_MAPPING




BERT_VARIANTS = {
    "bert": {},
    "medbert": dict(
        hidden_size=192,
        intermediate_size=64,
        num_attention_heads=6,
        num_hidden_layers=6,
        hidden_dropout_prob=0.1,
        attention_probs_dropout_prob=0.1,
    ),

    "cehrbert": dict(
        hidden_size=128,
        intermediate_size=2048,
        num_hidden_layers=12,
        num_attention_heads=8,
        hidden_dropout_prob=0.1,
        attention_probs_dropout_prob=0.1,
    ),

    "behrt": dict(
        hidden_size=288,
        intermediate_size=512,
        num_attention_heads=12,
        num_hidden_layers=6,
        hidden_dropout_prob=0.1,
        attention_probs_dropout_prob=0.1,
    ),

    "hibehrt": dict(
        hidden_size=150,
        intermediate_size=108,
        num_attention_heads=6,
        num_hidden_layers=4,
        hidden_dropout_prob=0.2,
        attention_probs_dropout_prob=0.3,
    ),
}



def get_config_and_model_cls(model_type: str, mode: str = "mlm", variant: str = None):
    assert mode in ["mlm", "eval", "causal"]

    if model_type not in CONFIG_MAPPING:
        raise ValueError(f"Unknown model_type: {model_type}")

    config_cls = CONFIG_MAPPING[model_type]

    if mode == "mlm":
        model_cls = MODEL_FOR_MASKED_LM_MAPPING[config_cls]
    elif mode == "eval":
        model_cls = MODEL_MAPPING[config_cls]
    else:
        model_cls = MODEL_FOR_CAUSAL_LM_MAPPING[config_cls]

    variant_kwargs = {}
    if variant is not None and issubclass(config_cls, BertConfig):
        variant_kwargs = BERT_VARIANTS.get(variant, {})
        if variant not in BERT_VARIANTS:
            raise ValueError(f"Unknown BERT variant: {variant}")

    def build_config(**kwargs):
        return config_cls(**variant_kwargs, **kwargs)

    return build_config, model_cls


def fix_roberta_longformer_max_pos(cfg):

    model_type = getattr(cfg, "model_type", "").lower()

    if model_type == "roberta":
        if cfg.max_position_embeddings == 512:
            cfg.max_position_embeddings = 513

    elif model_type == "longformer":
        if cfg.max_position_embeddings == 512:
            cfg.max_position_embeddings = 4097

    return cfg



def load_config_with_env(path):
    # read file
    with open(path, "r") as f:
        raw_text = f.read()
    expanded = os.path.expandvars(raw_text)
    
    return yaml.safe_load(expanded)


class Time2Vec(nn.Module):

    def __init__(
        self,
        in_features: int = 1,
        out_features: int = 16,
        periodic_activation: Callable = torch.sin,
    ):
        super().__init__()
        assert out_features >= 1, "out_features must be >= 1"

        self.in_features = in_features
        self.out_features = out_features
        self.periodic_activation = periodic_activation

        self.W = nn.Parameter(torch.randn(in_features, out_features - 1))
        self.b = nn.Parameter(torch.randn(out_features - 1))

        self.W0 = nn.Parameter(torch.randn(in_features))
        self.b0 = nn.Parameter(torch.randn(1))

    def forward(self, tau: torch.Tensor) -> torch.Tensor:

        v1 = self.periodic_activation(tau @ self.W + self.b)
        v2 = (tau @ self.W0).unsqueeze(-1) + self.b0

        return torch.cat([v2, v1], dim=-1)
    

def get_rank():
    if not dist.is_available() or not dist.is_initialized():
        return 0
    return dist.get_rank()




def get_bootstrap_ci(
    y_true: torch.Tensor,
    y_score: torch.Tensor,
    num_iter: int = 1000,
    alpha: float = 0.05,
    ndigits: int = 3,
):
    device = y_score.device

    y_true = y_true.detach().view(-1).to(device).long()
    y_score = y_score.detach().view(-1).to(device)

    auroc_point = BinaryAUROC().to(device)(y_score, y_true)
    auprc_point = BinaryAveragePrecision().to(device)(y_score, y_true)

    n = y_true.numel()
    auroc_samples = torch.empty(num_iter, device=device)
    auprc_samples = torch.empty(num_iter, device=device)

    for i in range(num_iter):
        idx = torch.randint(0, n, (n,), device=device)
        auroc_samples[i] = BinaryAUROC().to(device)(y_score[idx], y_true[idx])
        auprc_samples[i] = BinaryAveragePrecision().to(device)(y_score[idx], y_true[idx])

    # Percentile CI
    q_low = alpha / 2.0         # 2.5%
    q_high = 1.0 - alpha / 2.0  # 97.5%

    auroc_low = torch.quantile(auroc_samples, q_low)
    auroc_high = torch.quantile(auroc_samples, q_high)

    auprc_low = torch.quantile(auprc_samples, q_low)
    auprc_high = torch.quantile(auprc_samples, q_high)

    def _fmt(point, low, high):
        p = float(point.detach().cpu())
        l = float(low.detach().cpu())
        h = float(high.detach().cpu())
        return f"{round(p, ndigits)} ({round(l, ndigits)}, {round(h, ndigits)})"

    auroc_text = _fmt(auroc_point, auroc_low, auroc_high)
    auprc_text = _fmt(auprc_point, auprc_low, auprc_high)

    return auroc_text, auprc_text


def gather_1d_varlen_pl(module, x: torch.Tensor) -> torch.Tensor:
    x = x.detach().view(-1)

    if not getattr(module, "trainer", None) or module.trainer.world_size == 1:
        return x

    device = x.device
    local_len = torch.tensor([x.numel()], device=device, dtype=torch.long)

    all_lens = module.all_gather(local_len).view(-1) 
    max_len = int(all_lens.max().item())

    if x.numel() < max_len:
        pad = torch.zeros(max_len - x.numel(), device=device, dtype=x.dtype)
        x_pad = torch.cat([x, pad], dim=0)
    else:
        x_pad = x

    x_gather = module.all_gather(x_pad)

    chunks = []
    for r in range(x_gather.shape[0]):
        chunks.append(x_gather[r, : int(all_lens[r].item())])
    return torch.cat(chunks, dim=0)


def log_bootstrap_ci_text_percentile(
    module,
    y_true: torch.Tensor,
    y_score: torch.Tensor,
    prefix: str = "test",
    num_iter: int = 1000,
    alpha: float = 0.05,
    ndigits: int = 3,
):
    y_all = gather_1d_varlen_pl(module, y_true)
    s_all = gather_1d_varlen_pl(module, y_score)

    if not getattr(module, "trainer", None) or module.trainer.is_global_zero:
        auroc_ci_text, auprc_ci_text = get_bootstrap_ci(
            y_true=y_all,
            y_score=s_all,
            num_iter=num_iter,
            alpha=alpha,
            ndigits=ndigits,
        )

        # Use wandb.log directly for string-based CI values
        wandb.log({
            f"{prefix}_auroc_ci": auroc_ci_text,
            f"{prefix}_auprc_ci": auprc_ci_text,
        }, commit=False)

In [45]:
import os
import torch


import lightning as lt
import torch.nn as nn
import torch.nn.functional as F
from typing import Any, Dict, Optional

from torchmetrics.classification import Accuracy, BinaryAUROC, BinaryAveragePrecision




class EHREmbeddings(nn.Module):
    def __init__(
        self,
        vocab_size: int,
        embedding_size: int,
        pad_token_id: int = 0,
        type_vocab_size: int = 28,
        visit_vocab_size: int = 102,
        stage_vocab_size: int = 5,
        dropout: float = 0.1,
        use_position_embeddings: bool = False,
        max_position_embeddings: int = 0,
        use_time: bool = False,
        time_in_features: int = 1,
        time_out_features: int = 16,
        use_numeric: bool = False,
        numeric_hidden_size: int = 16,   
    ):
        super().__init__()

        self.tok_emb   = nn.Embedding(vocab_size,       embedding_size, padding_idx=pad_token_id)
        self.type_emb  = nn.Embedding(type_vocab_size,  embedding_size, padding_idx=pad_token_id)
        self.visit_emb = nn.Embedding(visit_vocab_size, embedding_size, padding_idx=pad_token_id)
        self.stage_emb = nn.Embedding(stage_vocab_size, embedding_size, padding_idx=pad_token_id)

        
        self.use_position_embeddings = use_position_embeddings
        if use_position_embeddings:
            if max_position_embeddings <= 0:
                raise ValueError("max_position_embeddings must be > 0 when use_position_embeddings=True")
            self.pos_emb = nn.Embedding(max_position_embeddings, embedding_size)
        else:
            self.pos_emb = None

        
        self.use_time = use_time
        if use_time:
            self.time2vec = Time2Vec(
                in_features=time_in_features,
                out_features=time_out_features,
                periodic_activation=torch.sin,
            )
            self.time_proj = nn.Linear(time_out_features, embedding_size)
        else:
            self.time2vec = None
            self.time_proj = None

        
        self.use_numeric = use_numeric
        if use_numeric:
            self.numeric_hidden_size = numeric_hidden_size
            
            self.num_proj1 = nn.Linear(1, numeric_hidden_size)
            self.num_proj2 = nn.Linear(numeric_hidden_size, embedding_size)
            self.num_act = nn.GELU()

            
            self.null_numeric = nn.Parameter(torch.zeros(embedding_size))
            nn.init.normal_(self.null_numeric, mean=0.0, std=0.02)

            nn.init.xavier_uniform_(self.num_proj1.weight)
            nn.init.zeros_(self.num_proj1.bias)
            nn.init.xavier_uniform_(self.num_proj2.weight)
            nn.init.zeros_(self.num_proj2.bias)
        else:
            self.num_proj1 = None
            self.num_proj2 = None
            self.num_act = None
            self.null_numeric = None

        self.norm = nn.LayerNorm(embedding_size)
        self.drop = nn.Dropout(dropout)

    def encode(
        self,
        input_ids,
        type_ids,
        visit_ids,
        stage_ids,
        time_feats=None,          
        numeric_values=None,     
        numeric_mask=None,        
    ):
        
        x = self.tok_emb(input_ids.long())
        x = x + self.type_emb(type_ids.long())
        x = x + self.visit_emb(visit_ids.long())
        x = x + self.stage_emb(stage_ids.long())

        
        if self.pos_emb is not None:
            shape = input_ids.size()
            seqlen = shape[-1]

            position_ids = torch.arange(seqlen, device=input_ids.device)

            if input_ids.dim() == 2:        
                bsz = shape[0]
                position_ids = position_ids.unsqueeze(0).expand(bsz, seqlen)          
            elif input_ids.dim() == 3:        
                bsz, n = shape[0], shape[1]
                position_ids = position_ids.view(1, 1, seqlen).expand(bsz, n, seqlen) 
            else:
                raise ValueError(f"Unsupported input_ids.dim()={input_ids.dim()}")
            x = x + self.pos_emb(position_ids)

        
        if self.use_time:
            if time_feats is None:
                raise ValueError("time_feats must be provided when use_time=True")
            if time_feats.dim() == 2:
                time_feats = time_feats.unsqueeze(-1)
            elif time_feats.dim() != 3:
                raise ValueError(f"Unexpected time_feats.dim()={time_feats.dim()}, expected 2 or 3")
            t = self.time2vec(time_feats.float())   
            t = self.time_proj(t)                   
            x = x + t

        
        if self.use_numeric:
            if numeric_values is None or numeric_mask is None:
                raise ValueError("numeric_values and numeric_mask must be provided when use_numeric=True")

            
            v = numeric_values.float().unsqueeze(-1)       
            
            h = self.num_act(self.num_proj1(v))             
            num_emb = self.num_proj2(h)                     

            mask = numeric_mask.bool().unsqueeze(-1)        
            num_emb = torch.where(mask, num_emb, self.null_numeric.view(1, 1, -1))
            x = x + num_emb

        return self.drop(self.norm(x))

    def forward(self, input_ids=None, token_type_ids=None, inputs_embeds=None, **kwargs):
        if inputs_embeds is not None:
            return inputs_embeds
        x = self.tok_emb(input_ids.long())
        return self.drop(self.norm(x))

In [46]:

import json
import torch
import numpy as np
import polars as pl

import torch.nn as nn
from tqdm import tqdm
from datasets import load_from_disk
from collections import defaultdict
from transformers import RoFormerModel


from typing import List, Dict, Union, Optional
from chromadb.api.types import Documents, Embeddings, EmbeddingFunction



class EHREmbedder(nn.Module):
    def __init__(
        self,
        config,
        backbone,
        ckpt_path: Optional[str] = None,
        dropout: float = 0.1,
        pooling: str = "cls",
        normalize: bool = False,
        use_numeric: bool = False, # not to be used, but implemenetd for future research, Keep always False
        use_time: bool = False, # not to be used, but implemenetd for future research, Keep always False
        device: Optional[str] = None,
        dtype: torch.dtype = torch.float32,
    ):
        super().__init__()
        self.config = config
        self.pooling = pooling
        self.normalize = normalize
        self.dtype_ = dtype
        self.device_ = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.backbone = backbone(config)
        self.use_time = use_time
        self.use_numeric = use_numeric
        
        if self.use_time or self.use_numeric:
            raise ValueError("not to be used, but implemenetd for future research, Keep always False")
            
        rope_model_types = {"modernbert", "roformer"}
        model_type = getattr(config, "model_type", "").lower()
        is_rope = model_type in rope_model_types
        
        self.ehr_embeddings = EHREmbeddings(
            vocab_size=config.vocab_size,
            embedding_size=getattr(config, "hidden_size", getattr(config, "embedding_size")),
            pad_token_id=config.pad_token_id,
            type_vocab_size=config.type_vocab_size,
            visit_vocab_size=config.visit_vocab_size,
            stage_vocab_size=config.stage_vocab_size,
            dropout=dropout,
            use_position_embeddings=not is_rope,
            max_position_embeddings=(getattr(config, "max_position_embeddings", 0) if not is_rope else 0),
            use_time=self.use_time,
            time_in_features=1,
            time_out_features=16,
            use_numeric=self.use_numeric,
        )

        if ckpt_path:
            self.load_pretrained_weights(ckpt_path)

        self.eval().to(self.device_, dtype=self.dtype_)

    @torch.no_grad()
    def encode(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        type_ids: torch.Tensor,
        visit_ids: torch.Tensor,
        stage_ids: torch.Tensor,
        time_feats: Optional[torch.Tensor] = None,
        numeric_values: Optional[torch.Tensor] = None,
        numeric_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        if (time_feats is not None) or (numeric_values is not None) or (numeric_mask is not None):
            raise ValueError(
                "EHREmbedder.encode: time/numeric tensors were passed but are disabled. "
                "Pass None for time_feats/numeric_values/numeric_mask.")
        
        inputs_embeds = self.ehr_embeddings.encode(
            input_ids=input_ids.to(self.device_),
            type_ids=type_ids.to(self.device_),
            visit_ids=visit_ids.to(self.device_),
            stage_ids=stage_ids.to(self.device_),
            time_feats=(time_feats.to(self.device_) if time_feats is not None else None),
            numeric_values=(numeric_values.to(self.device_) if numeric_values is not None else None),
            numeric_mask=(numeric_mask.to(self.device_) if numeric_mask is not None else None)).to(self.dtype_)

        outputs = self.backbone(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask.to(self.device_),
            output_hidden_states=False,
            return_dict=True,
        )
        last_hidden = outputs.last_hidden_state  

        if self.pooling == "cls":
            vec = last_hidden[:, 0, :]
        elif self.pooling == "mean":
            mask = attention_mask.unsqueeze(-1).to(device=last_hidden.device,dtype=last_hidden.dtype) 
            vec = (last_hidden * mask).sum(dim=1) / (mask.sum(dim=1).clamp(min=1.0))
        else:
            raise ValueError(f"Unsupported pooling='{self.pooling}' (use 'cls' or 'mean')")

        if self.normalize:
            vec = nn.functional.normalize(vec, p=2, dim=-1)
        return vec

    def load_pretrained_weights(self, ckpt_path: str) -> None:
        sd_obj = torch.load(ckpt_path, map_location="cpu", weights_only=False)
        sd = sd_obj["state_dict"] if isinstance(sd_obj, dict) and "state_dict" in sd_obj else sd_obj

        mt = getattr(self.config, "model_type", "").lower()
        prefix_map = {
            "bert":       "backbone.bert.",
            "roberta":    "backbone.roberta.",
            "longformer": "backbone.longformer.",
            "modernbert": "backbone.model.",
            "roformer":   "backbone.roformer.",
            "big_bird":   "backbone.bert.",
            "mamba":      "backbone.backbone.",
            "mamba2":     "backbone.backbone."}
        backbone_prefix = prefix_map.get(mt, None)

        DROP_PREFIXES = ["backbone.cls.", "top_1_train.", "top_1_val.", "backbone.lm_head.", 
                         "classifier.", "cls.", "lm_head.", "score."]
        remapped = {}
        for k, v in sd.items():
            if any(k.startswith(dp) for dp in DROP_PREFIXES):
                continue

            if k.startswith("ehr_embeddings."):
                new_k = k
            elif backbone_prefix and k.startswith(backbone_prefix):
                new_k = "backbone." + k[len(backbone_prefix):]
            elif k.startswith("backbone."):
                new_k = k
            else:
                new_k = k

            remapped[new_k] = v
        missing, unexpected = self.load_state_dict(remapped, strict=False)
        print("Embedder weights loaded.")
        print("missing keys:", missing)
        print("unexpected keys:", unexpected)


class EmbedCollator:
    def __init__(self) -> None:
        self.embed_keys = ("input_ids", "attention_mask", "visit_ids", "stage_ids", "type_ids")

    def __call__(self, batch: List[Union[Dict, List[Dict]]]) -> Dict[str, torch.Tensor]:
        chunks = self._flatten(batch)
        return self._stack(chunks)

    def _flatten(self, batch) -> List[Dict]:
        out = []
        for item in batch:
            if isinstance(item, dict):
                out.append(item)
            elif isinstance(item, (list, tuple)):
                out.extend(item)
            else:
                raise TypeError(f"Unexpected item type: {type(item)}")
        if not out:
            raise ValueError("Empty batch after normalization.")
        return out

    def _stack(self, chunks: List[Dict]) -> Dict[str, torch.Tensor]:
        out = {}
        for k in self.embed_keys:
            seq_list = []
            for c in chunks:
                v = c.get(k, None)
                if isinstance(v, list):
                    v = [0 if x is None else x for x in v]
                elif v is None:
                    v = 0
                seq_list.append(torch.as_tensor(v))
            out[k] = torch.stack(seq_list, 0)
        return out
    


class ChromaEHREmbeddingFunction:
    def __init__(self, embedder, collate_fn, batch_size: Optional[int] = None):
        self.embedder = embedder
        self.collate_fn = collate_fn
        self.batch_size = batch_size 

    def _decode_docs(self, docs: Documents):
        out: List[Union[dict, list]] = []
        for item in docs:
            if isinstance(item, str):
                out.append(json.loads(item))
            elif isinstance(item, (list, tuple)):
                out.append([json.loads(x) if isinstance(x, str) else x for x in item])
            else:
                out.append(item)
        return out

    def _slice_batch(self, batch_tensors: Dict[str, torch.Tensor], sl: slice) -> Dict[str, torch.Tensor]:
        # Required
        keys = ["input_ids", "attention_mask", "type_ids", "visit_ids", "stage_ids"]
        # Optional (only pass if present)
        for opt in ["time_diff", "numeric_values", "numeric_mask"]:
            if opt in batch_tensors:
                keys.append(opt)
        return {k: batch_tensors[k][sl] for k in keys}
    
    def name(self) -> str:
        return self.embedder.config.model_type
    
    def __call__(self, input: Documents) -> Embeddings:
        # 1) Decode JSON if needed
        docs = self._decode_docs(input)
        batch_inputs = self.collate_fn(docs)
        device = getattr(self.embedder, "device_", "cpu")

        req_long = ["input_ids", "attention_mask", "type_ids", "visit_ids", "stage_ids"]
        
        for k in req_long:
            if k not in batch_inputs:
                raise KeyError(f"Missing required key '{k}' in collated batch.")
            batch_inputs[k] = batch_inputs[k].to(device=device, dtype=torch.long)

        if "time_diff" in batch_inputs:
            batch_inputs["time_diff"] = batch_inputs["time_diff"].to(device=device)
        if "numeric_values" in batch_inputs:
            batch_inputs["numeric_values"] = batch_inputs["numeric_values"].to(device=device)
        if "numeric_mask" in batch_inputs:
            batch_inputs["numeric_mask"] = batch_inputs["numeric_mask"].to(device=device)

        B = batch_inputs["input_ids"].size(0)
        bs = self.batch_size or B

        embs_out: List[torch.Tensor] = []
        with torch.no_grad():
            for start in range(0, B, bs):
                end = min(start + bs, B)
                sub = self._slice_batch(batch_inputs, slice(start, end))
                v = self.embedder.encode(
                    input_ids=sub["input_ids"],
                    attention_mask=sub["attention_mask"],
                    type_ids=sub["type_ids"],
                    visit_ids=sub["visit_ids"],
                    stage_ids=sub["stage_ids"],
#                     time_feats=sub.get("time_diff", None), uncomment if use time is true and want it to be embedded
#                     numeric_values=sub.get("numeric_values", None), Same above
#                     numeric_mask=sub.get("numeric_mask", None), same above
                )
                embs_out.append(v.detach().cpu())

        return torch.cat(embs_out, dim=0).tolist()
    


class VectorDBUploader:
    def __init__(
        self,
        collection,
        seq_gen,
        main_window: str,
        seq_length: int,
        limits: dict,
        data_idx_path: str,
        data_path: str,
        use_time: bool = False, # set as true for values storage only
        use_numeric: bool = False, # set as true for values storage only
        add_cls_per_chunk: bool = True,
        needed_cols: list = None,
    ):
        self.collection = collection
        self.seq_gen = seq_gen
        self.main_window = main_window
        self.seq_length = seq_length
        self.limits = limits
        self.use_time = use_time 
        self.use_numeric = use_numeric
        self.add_cls_per_chunk = add_cls_per_chunk

        if needed_cols is None:
            needed_cols = ["subject_id", "input_ids", "attention_mask", "visit_ids", "stage_ids", "type_ids"]
            
            if self.use_time :
                needed_cols.append("time_diff")
            if self.use_numeric:
                needed_cols += ["numeric_values", "numeric_mask"]
                
        self.needed_cols = needed_cols
        
        
        self.data_idx = pl.read_parquet(data_idx_path)
        sub_ids = set(self.data_idx.get_column("subject_id").to_list())

        hf_dataset = load_from_disk(data_path)
        hf_dataset = hf_dataset.filter(
            lambda sids: [sid in sub_ids for sid in sids],
            batched=True,
            input_columns="subject_id")

        self.hf_dataset = (hf_dataset
                           .flatten_indices()
                           .select_columns(self.needed_cols)
                           .with_format("numpy", columns=self.needed_cols, 
                                        output_all_columns=False))

        self.index = self._build_index()

    def _build_index(self):
        sids = self.hf_dataset["subject_id"]
        index = defaultdict(list)
        for i, sid in enumerate(sids):
            index[sid].append(i)
        return index

    def _to_list(self, v):
        if isinstance(v, np.ndarray):
            return v.tolist()
        if isinstance(v, list):
            return v
        return v

#     def _ensure_optional_fields(self, chunk: dict):
#         L = len(chunk["input_ids"])
#         if self.use_time:
#             if "time_diff" not in chunk or chunk["time_diff"] is None:
#                 chunk["time_diff"] = [0.0] * L
#             else:
#                 chunk["time_diff"] = [0.0 if x is None else float(x) for x in chunk["time_diff"]]
#         if self.use_numeric:
#             if "numeric_values" not in chunk or chunk["numeric_values"] is None:
#                 chunk["numeric_values"] = [0.0] * L
#             else:
#                 chunk["numeric_values"] = [0.0 if x is None else float(x) for x in chunk["numeric_values"]]
#             if "numeric_mask" not in chunk or chunk["numeric_mask"] is None:
#                 chunk["numeric_mask"] = [0] * L
#             else:
#                 chunk["numeric_mask"] = [0 if x is None else int(x) for x in chunk["numeric_mask"]]

#         return chunk

    def upsert_chunks(self):
        for row_idx in tqdm(range(len(self.data_idx))):
            stay = self.data_idx[row_idx]
            split = stay["split"][0]
            
            subject_id = stay["subject_id"][0]
            
            start_key_or_int = self.limits[self.main_window][self.seq_length][0]
            end_key = self.limits[self.main_window][self.seq_length][1]
            
            start = stay[start_key_or_int][0] if isinstance(start_key_or_int, str) else int(start_key_or_int)
            end = stay[end_key][0] if isinstance(end_key, str) else int(end_key)
            
            timeline_encoded = self.hf_dataset.select(self.index[subject_id])[0]
            
            history_window = {k: self._to_list(v) for k, v in timeline_encoded.items()}
            history_window = {k: (v[start:end] if isinstance(v, list) else v) for k, v in history_window.items()}
            
            chunks = self.seq_gen.get_overlapped_chunks(history_window,
                                                        add_cls_per_chunk=self.add_cls_per_chunk)
            docs, ids, metas = [], [], []
            
            for ci, ch in enumerate(chunks):
#                 ch = self._ensure_optional_fields(ch)
                doc_dict = {"input_ids": ch["input_ids"],
                            "attention_mask": ch["attention_mask"],
                            "visit_ids": ch["visit_ids"],
                            "stage_ids": ch["stage_ids"],
                            "type_ids": ch["type_ids"]}
                docs.append(json.dumps(doc_dict, separators=(",", ":")))
                ids.append(f"{subject_id}__{row_idx:06d}__{ci:04d}")
                meta = {"subject_id": int(subject_id),
                        "stay_row": int(row_idx),
                        "chunk_idx": int(ci),
                        "split": str(split),
                        "window": str(self.main_window),
                        "seq_length": int(self.seq_length),}

                if self.use_time:
                    meta["time_diff"] = json.dumps(ch["time_diff"], separators=(",", ":"))
                if self.use_numeric:
                    meta["numeric_values"] = json.dumps(ch["numeric_values"], separators=(",", ":"))
                    meta["numeric_mask"] = json.dumps(ch["numeric_mask"], separators=(",", ":"))

                metas.append(meta)

            self.collection.upsert(ids=ids, documents=docs, metadatas=metas)
            del timeline_encoded, history_window, chunks, docs, ids, metas

In [47]:
from transformers import RoFormerConfig, RoFormerModel
seq_gen = SequencesGenerator(tokenizer_path='../vocab.json',
                            chunk_length=1024,
                            overlap=0)

# IMPORTANT
VOCAB_SIZE = 47377
config = RoFormerConfig(vocab_size=VOCAB_SIZE,
                        hidden_size=768,
                        num_hidden_layers=12,
                        num_attention_heads=12,
                        intermediate_size=3072,
                        max_position_embeddings=1536,
                        pad_token_id=0,
                        type_vocab_size= 28,
                        visit_vocab_size= 102,
                        stage_vocab_size= 5)


embedder = EHREmbedder(
    config=config,
    backbone=RoFormerModel,
    ckpt_path="/scratch/sas10092/ehr-foundation/models/mlm/wandb/run-20251128_073215-roformer_13218339_1024_128_15_maskprob_12_5overlap/files/ckpt/epoch=65-step=665082.ckpt",
    pooling="mean",                        
    normalize=True)

collate_fn = EmbedCollator()

top_k = 10
train_dataset = RetrievalEvalDataset(dataset_path='../data/meds_normalized_arrow/',
                            data_idx_path='../downstream_idx.parquet',
                            seq_gen=seq_gen,
                            embedder = embedder,
                            collate_fn= collate_fn,
                            limits_dict=limits,
                            vectordb_path='/scratch/sas10092/ehr-foundation/data/vectordbs/roformer/mean/within48_hist_full_1024_128',
                            task='y_mort',
                            main_window='within48_query',
                            seq_length=1024,
                            top_k=top_k,
                            use_time=True,
                            use_numeric=True,
                            add_cls=True,
                            split='train')

Embedder weights loaded.
missing keys: []
unexpected keys: []

Loading dataset from disk:   0%|          | 0/70 [00:00<?, ?it/s]

In [48]:
chunk_collator = EvalCollator()
retrieval_collator = RetrievalCollator(chunk_collator=chunk_collator, top_k=top_k)

In [49]:
# x = train_dataset[7468]

In [50]:
i = 7468
stay = train_dataset.data_idx[i]
print(stay)

shape: (1, 54)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ hadm_id  ┆ hosp_admi ┆ hosp_disc ┆ … ┆ wStay_sta ┆ wStay_end ┆ wStay_sta ┆ wStay_end │
│ d         ┆ ---      ┆ ssion_tim ┆ harge_tim ┆   ┆ rt_1024   ┆ _1024     ┆ rt_1536   ┆ _1536     │
│ ---       ┆ i64      ┆ e         ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
│           ┆          ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 11748036  ┆ 27197593 ┆ 2124-11-2 ┆ 2124-11-2 ┆ … ┆ 1075      ┆ 2098      ┆ 563       ┆ 2098      │
│           ┆          ┆ 3         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 22:07:00  ┆ 17:00:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [51]:
sid = int(stay["subject_id"][0])
start = stay[train_dataset.start_limit][0]
end   = stay[train_dataset.end_limit][0]

timeline = train_dataset.hf_dataset.select(train_dataset.index[sid])[0]
timeline = {k: train_dataset._to_py(v) for k, v in timeline.items()}

print("timeline length:", len(timeline["input_ids"]))
print("slice length:", end - start)

timeline length: 7086
slice length: 1023

In [52]:
query_window = {
    k: (v[start:end] if isinstance(v, list) else v)
    for k, v in timeline.items()
}

query_chunks = train_dataset.seq_gen.get_overlapped_chunks(
    query_window,
    chunk_length=train_dataset.seq_length,
    overlap=0,
    add_cls_per_chunk=train_dataset.add_cls,
)

qc = query_chunks[0]
print("query attention sum:", sum(qc["attention_mask"]))

query attention sum: 1024

In [53]:
history = train_dataset._query_vectordb(
    subject_id=sid,
    query_chunk=qc
)

print("num retrieved:", len(history))

for k, ch in enumerate(history):
    am = ch["attention_mask"]
    s = sum(am)
    print(f"k={k} attention_sum={s}")

num retrieved: 6
k=0 attention_sum=1024
k=1 attention_sum=1024
k=2 attention_sum=1024
k=3 attention_sum=906
k=4 attention_sum=1024
k=5 attention_sum=411

In [55]:
bad_ch = history[6]

for key in ["input_ids", "attention_mask", "visit_ids", "stage_ids", "type_ids"]:
    uniq = set(bad_ch[key])
    print(key, "unique:", list(uniq)[:5])

IndexError: list index out of range

In [56]:
bad_idx = 7468

In [57]:
item = train_dataset[bad_idx]
print(len(item["history"]))   # expect < top_k

6

In [58]:
batch = [item]
collated = retrieval_collator(batch)

In [59]:
h_am = collated["history"]["attention_mask"][0]   # (K, L)

sums = h_am.sum(dim=1)
print(sums)

tensor([1024, 1024, 1024,  906, 1024,  411,    1,    1,    1,    1])

In [60]:
bad_k = (sums == 0).nonzero(as_tuple=True)[0].item()
print("bad_k:", bad_k)

RuntimeError: a Tensor with 0 elements cannot be converted to Scalar

In [61]:
print("raw retrieved:", len(item["history"]))
print("top_k:", retrieval_collator.top_k)

raw retrieved: 6
top_k: 10

In [62]:
for k, v in collated["history"].items():
    if isinstance(v, torch.Tensor):
        print(k, v[0, bad_k].unique())

input_ids tensor([0, 2])
attention_mask tensor([0, 1])
visit_ids tensor([0])
stage_ids tensor([0])
type_ids tensor([0])
time_diff tensor([0.])
numeric_values tensor([0.])
numeric_mask tensor([False])

In [63]:
bad_ks = (sums == 0).nonzero(as_tuple=True)[0]
print("bad_ks:", bad_ks.tolist())

bad_ks: []

In [64]:
bad_k = bad_ks[0].item()
print("bad_k:", bad_k)

IndexError: index 0 is out of bounds for dimension 0 with size 0

In [65]:
for bk in bad_ks.tolist():
    print("\n=== padded history chunk k =", bk, "===")
    for k, v in collated["history"].items():
        if isinstance(v, torch.Tensor):
            print(k, v[0, bk].unique().tolist())

In [67]:
idx = 7468  # example bad idx you logged

ds = train_dataset  # RetrievalEvalDataset
sample = ds[idx]

print("label:", sample["label"])
print("query keys:", sample["query"].keys())
print("num retrieved:", len(sample["history"]))

label: 0.0
query keys: dict_keys(['input_ids', 'attention_mask', 'visit_ids', 'stage_ids', 'type_ids', 'numeric_values', 'numeric_mask', 'time_diff'])
num retrieved: 6

In [68]:
q = sample["query"]
print("query attention sum:", sum(q["attention_mask"]))
print("query length:", len(q["input_ids"]))

query attention sum: 1024
query length: 1024

In [69]:
history = sample["history"]

for k, ch in enumerate(history):
    attn_sum = sum(ch["attention_mask"])
    print(f"k={k} attention_sum={attn_sum}")

k=0 attention_sum=1024
k=1 attention_sum=1024
k=2 attention_sum=1024
k=3 attention_sum=906
k=4 attention_sum=1024
k=5 attention_sum=411

In [70]:
 collated = retrieval_collator([sample])

h_mask = collated["history"]["attention_mask"][0]  # (K, L)
sums = h_mask.sum(dim=1)

print("history attention sums:", sums.tolist())

history attention sums: [1024, 1024, 1024, 906, 1024, 411, 1, 1, 1, 1]

In [71]:
bad_ks = (sums == 0).nonzero(as_tuple=True)[0].tolist()
print("bad ks:", bad_ks)

for k in bad_ks:
    print(f"\n=== BAD HISTORY CHUNK k={k} ===")
    for key in collated["history"]:
        v = collated["history"][key][0, k]
        print(key, v.unique().tolist())

bad ks: []

In [1]:
import polars as pl
import os
from tqdm.notebook import tqdm

In [2]:
pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000)

In [89]:
df = pl.read_parquet('../downstream_idx.parquet')

In [99]:
df.filter(pl.col('split') == 'test').filter(pl.col('y_mort_1yr') == 1).shape

(1017, 54)

In [100]:
df.filter(pl.col('split') == 'test').filter(pl.col('y_mort_1yr') == 0).shape

(11346, 54)

In [101]:
round(1017/(1017 + 11346)*100,3)

8.226

In [102]:
100 - round(1017/(1017 + 11346)*100,3)

91.774

In [66]:
df

shape: (61_175, 54)
┌────────────┬──────────┬─────────────────────┬─────────────────────┬───┬──────────────────┬────────────────┬──────────────────┬────────────────┐
│ subject_id ┆ hadm_id  ┆ hosp_admission_time ┆ hosp_discharge_time ┆ … ┆ wStay_start_1024 ┆ wStay_end_1024 ┆ wStay_start_1536 ┆ wStay_end_1536 │
│ ---        ┆ ---      ┆ ---                 ┆ ---                 ┆   ┆ ---              ┆ ---            ┆ ---              ┆ ---            │
│ i64        ┆ i64      ┆ datetime[μs]        ┆ datetime[μs]        ┆   ┆ i64              ┆ i64            ┆ i64              ┆ i64            │
╞════════════╪══════════╪═════════════════════╪═════════════════════╪═══╪══════════════════╪════════════════╪══════════════════╪════════════════╡
│ 10000690   ┆ 25860671 ┆ 2150-11-02 18:02:00 ┆ 2150-11-12 13:45:00 ┆ … ┆ 3765             ┆ 4788           ┆ 3253             ┆ 4788           │
│ 10001217   ┆ 24597018 ┆ 2157-11-18 22:56:00 ┆ 2157-11-25 18:00:00 ┆ … ┆ 550              ┆ 1573           ┆ 127              ┆ 1573           │
│ 10001725   ┆ 25563031 ┆ 2110-04-11 15:08:00 ┆ 2110-04-14 15:00:00 ┆ … ┆ 219              ┆ 1242           ┆ 29               ┆ 1242           │
│ 10001884   ┆ 26184834 ┆ 2131-01-07 20:39:00 ┆ 2131-01-20 05:15:00 ┆ … ┆ 17536            ┆ 18559          ┆ 17024            ┆ 18559          │
│ 10002013   ┆ 23581541 ┆ 2160-05-18 07:45:00 ┆ 2160-05-23 13:30:00 ┆ … ┆ 1811             ┆ 2834           ┆ 1299             ┆ 2834           │
│ …          ┆ …        ┆ …                   ┆ …                   ┆ … ┆ …                ┆ …              ┆ …                ┆ …              │
│ 19999297   ┆ 21439025 ┆ 2162-08-14 23:55:00 ┆ 2162-08-23 04:16:00 ┆ … ┆ 9364             ┆ 10387          ┆ 8852             ┆ 10387          │
│ 19999442   ┆ 26785317 ┆ 2148-11-19 10:00:00 ┆ 2148-12-04 16:25:00 ┆ … ┆ 6428             ┆ 7451           ┆ 5916             ┆ 7451           │
│ 19999828   ┆ 25744818 ┆ 2149-01-08 16:44:00 ┆ 2149-01-18 17:00:00 ┆ … ┆ 1489             ┆ 2512           ┆ 977              ┆ 2512           │
│ 19999840   ┆ 21033226 ┆ 2164-09-10 13:47:00 ┆ 2164-09-17 13:42:00 ┆ … ┆ 7139             ┆ 8162           ┆ 6627             ┆ 8162           │
│ 19999987   ┆ 23865745 ┆ 2145-11-02 21:38:00 ┆ 2145-11-11 12:57:00 ┆ … ┆ 2037             ┆ 3060           ┆ 1525             ┆ 3060           │
└────────────┴──────────┴─────────────────────┴─────────────────────┴───┴──────────────────┴────────────────┴──────────────────┴────────────────┘