In [28]:
import os
import polars as pl
from tqdm.notebook import tqdm
pl.Config.set_tbl_rows(50)
pl.Config.set_fmt_float("full")

polars.config.Config

| Statistic | Delay (hours) |
|---|---:|
| Count | 66,106,991 |
| Null count | 696,048 |
| Mean | 1.479 |
| Standard deviation | 6.791 |
| Minimum | -6263.000 |
| 25% | 0.000 |
| 50% | 1.000 |
| 75% | 1.000 |
| Maximum | 8760.000 |

In [41]:
from collections import defaultdict
import os
import polars as pl
from tqdm.notebook import tqdm

data_path = '/scratch/sas10092/ehr-foundation/data/meds_normalized/data/train/'
downstream_idx = pl.read_parquet('/scratch/sas10092/ehr-foundation/resources/downstream_idx.parquet')


audit = {
    "within24": {
        "total": 0,
        "with_diagnosis": 0,
        "diagnosis_events": 0,
    },
    "within48": {
        "total": 0,
        "with_diagnosis": 0,
        "diagnosis_events": 0,
    },
    "within_stay": {
        "total": 0,
        "with_diagnosis": 0,
        "diagnosis_events": 0,
    },
}


for i in tqdm(range(len(downstream_idx))):

    stay = downstream_idx[i]

    subject_id = stay['subject_id'][0]
    shard = stay['shard'][0]

    q_start_24 = stay['w24_start_1024'][0]
    q_end_24 = stay['w24_end_1024'][0]

    q_start_48 = stay['w48_start_1024'][0]
    q_end_48 = stay['w48_end_1024'][0]

    q_start_st = stay['wStay_start_1024'][0]
    q_end_st = stay['wStay_end_1024'][0]


    shard_df = pl.read_parquet(
        os.path.join(data_path, shard)
    )

    timeline = shard_df.filter(
        pl.col('subject_id') == subject_id
    )


    queries = {
        "within24": timeline[q_start_24:q_end_24],
        "within48": timeline[q_start_48:q_end_48],
        "within_stay": timeline[q_start_st:q_end_st],
    }


    for name, query in queries.items():

        diagnosis_events = query.filter(
            pl.col('code').str.starts_with('DIAGNOSIS')
        )

        n_diag = diagnosis_events.height

        audit[name]["total"] += 1

        if n_diag > 0:
            audit[name]["with_diagnosis"] += 1

        audit[name]["diagnosis_events"] += n_diag



summary = []

for window, values in audit.items():

    summary.append({
        "window": window,
        "total_queries": values["total"],
        "queries_with_diagnosis": values["with_diagnosis"],
        "diagnosis_event_count": values["diagnosis_events"],
        "diagnosis_presence_rate": 
            values["with_diagnosis"] / values["total"]
    })


audit_summary = pl.DataFrame(summary)

audit_summary.write_parquet('audit_summary.parquet')

  0%|          | 0/61175 [00:00<?, ?it/s]

KeyboardInterrupt:

In [11]:
# audit

In [12]:
# timeline.filter(pl.col('code').str.starts_with('DIAGNOSIS'))

In [13]:
# downstream_idx.filter(pl.col('subject_id') == 10024043)

In [15]:
leakage_candidates = []
for i in tqdm(range(len(downstream_idx))):

    stay = downstream_idx[i]

    subject_id = stay["subject_id"][0]
    stay_id = stay["icustay_id"][0]
    shard = stay["shard"][0]

    shard_df = pl.read_parquet(
        os.path.join(data_path, shard)
    )

    timeline = shard_df.filter(
        pl.col("subject_id") == subject_id
    )

    windows = {
        "within24": (
            stay["w24_start_1024"][0],
            stay["w24_end_1024"][0],
        ),
        "within48": (
            stay["w48_start_1024"][0],
            stay["w48_end_1024"][0],
        ),
        "within_stay": (
            stay["wStay_start_1024"][0],
            stay["wStay_end_1024"][0],
        ),
    }
    
    for name, (start, end) in windows.items():

        query = timeline[start:end]

        diag = query.filter(
            pl.col("code").str.starts_with("DIAGNOSIS")
        )
        
        if diag.height > 0:
            
            leakage_candidates.append({
                "icustay_id": stay_id,
                "subject_id": subject_id,
                "window": name,
                "query_start_idx": start,
                "query_end_idx": end,
                "diagnosis_codes": diag["code"].to_list(),
                "diagnosis_times": diag["time"].to_list(),
            })

  0%|          | 0/61175 [00:00<?, ?it/s]

31342860
32895909
33060379
38688395
34510292
39558308
36575425
36081309
39492446
38860085
33958400
31559995
37521741
34728076
38922429
31350931
38989978
36594826
36827644
35736966
38860905
37801913
37801913
31097260
30321781
37831823
30950523
39911054
39911054
30273492
34706547
30546860
30492740
39789769
37804132
30137539
36091557
37915515
36161672
34619266
32381432
36324659
39242254
30354498
32040322
38552607
35141168
37898603
39485910
34969374
31969135
35896096
34692268
39953985
31145488
37159783
39177547
33349381

KeyboardInterrupt:

In [29]:
for i in range(len(leakage_candidates)):
    if leakage_candidates[i]['window'] == 'within24':
        print(i)
    elif leakage_candidates[i]['window'] == 'within48':
        print(i)

13
17
19
24
31
36
40
42
46
48
52
56
58
65
68
70
72
77
87
92
106
108
109
111
113
115
121
124
125
135
137
141
144
147
152
155
157
159
161
165
168
171
173
175
180
183
186
188
198
200
204
210
215
218
221
223
226
228

In [33]:
i = 108

In [34]:
subject_id = leakage_candidates[i]['subject_id']
print(subject_id)
icustay_id = leakage_candidates[i]['icustay_id']
print(icustay_id)
window = leakage_candidates[i]['window']
print(window)
 
query_start_idx = leakage_candidates[i]['query_start_idx']
print(query_start_idx)
query_end_idx = leakage_candidates[i]['query_end_idx']
print(query_end_idx)

stay = downstream_idx.filter(pl.col('icustay_id') == icustay_id)

print('\n------------\n')


subject_id = stay['subject_id'][0]
print(subject_id)
shard = stay['shard'][0]
print(shard)

if window == 'within24':
    q_start_24 = stay['w24_start_1024'][0]
    print(q_start_24)
    q_end_24 = stay['w24_end_1024'][0]
    print(q_end_24)

if window == 'within48':
    q_start_48 = stay['w48_start_1024'][0]
    print(q_start_48)
    q_end_48 = stay['w48_end_1024'][0]
    print(q_end_48)

if window == 'within_stay':
    q_start_st = stay['wStay_start_1024'][0]
    print(q_start_st)
    q_end_st = stay['wStay_end_1024'][0]
    print(q_end_st)

shard_df = pl.read_parquet(
    os.path.join(data_path, shard)
)

timeline = shard_df.filter(
    pl.col('subject_id') == subject_id
)

10067195
37801913
within24
268
1291

------------

10067195
261.parquet
268
1291

In [40]:
timeline[query_start_idx:query_end_idx]#.filter(pl.col('code').str.starts_with('DIAG'))

shape: (1_023, 69)
┌────────────┬──────────┬────────┬───────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ subject_id ┆ seq_id   ┆ out_id ┆ er_id ┆ … ┆ lab_descrip ┆ lab_frequen ┆ time_diff  ┆ numeric_va │
│ ---        ┆ ---      ┆ ---    ┆ ---   ┆   ┆ tion        ┆ cy          ┆ ---        ┆ lue/is_inl │
│ i64        ┆ f64      ┆ f64    ┆ f64   ┆   ┆ ---         ┆ ---         ┆ f64        ┆ ier        │
│            ┆          ┆        ┆       ┆   ┆ str         ┆ f64         ┆            ┆ ---        │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆            ┆ bool       │
╞════════════╪══════════╪════════╪═══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0.00012731 ┆ null       │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 4814814814 ┆            │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 8          ┆            │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0.00292824 ┆ null       │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 0740740741 ┆            │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0.02888888 ┆ true       │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 8888888888 ┆            │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ …          ┆ …        ┆ …      ┆ …     ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0.00069444 ┆ true       │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 4444444444 ┆            │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 5          ┆            │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0.00069444 ┆ null       │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 4444444444 ┆            │
│            ┆          ┆        ┆       ┆   ┆             ┆             ┆ 5          ┆            │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ null       │
│ 10067195   ┆ 21564201 ┆ null   ┆ null  ┆ … ┆ null        ┆ null        ┆ 0          ┆ true       │
└────────────┴──────────┴────────┴───────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [39]:
stay

shape: (1, 63)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ subject_i ┆ hadm_id  ┆ hosp_admi ┆ hosp_disc ┆ … ┆ wStay_sta ┆ wStay_end ┆ wStay_sta ┆ wStay_end │
│ d         ┆ ---      ┆ ssion_tim ┆ harge_tim ┆   ┆ rt_1536   ┆ _1536     ┆ rt_2048   ┆ _2048     │
│ ---       ┆ i64      ┆ e         ┆ e         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64       ┆          ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
│           ┆          ┆ datetime[ ┆ datetime[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10067195  ┆ 21564201 ┆ 2181-08-2 ┆ 2181-08-2 ┆ … ┆ 395       ┆ 1930      ┆ 100       ┆ 1930      │
│           ┆          ┆ 7         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ 06:48:00  ┆ 00:00:00  ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [73]:
audit_df = audit_df.with_columns(
    pl.col("diagnosis_times").cast(pl.Datetime)
)

In [115]:
# list(audit_df['subject_id'].unique())

In [102]:
# downstream_idx.filter(pl.col('icustay_id') == 38392119)

In [116]:
# stay = downstream_idx[0]

# subject_id = stay['subject_id'][0]
# shard = stay['shard'][0]

# q_start_24 = stay['w24_start_1024'][0]
# q_end_24 = stay['w24_end_1024'][0]

# q_start_48 = stay['w48_start_1024'][0]
# q_end_48 = stay['w48_end_1024'][0]

# q_start_st = stay['wStay_start_1024'][0]
# q_end_st = stay['wStay_end_1024'][0]

In [ ]:
import os
import polars as pl
from tqdm.notebook import tqdm
pl.Config.set_tbl_rows(50)
pl.Config.set_fmt_float("full")

In [11]:
data_path = '/scratch/sas10092/ehr-foundation/data/meds_normalized/data/train/'
downstream_idx = pl.read_parquet('/scratch/sas10092/ehr-foundation/resources/downstream_idx.parquet')

delay_threshold_hours = 1.5

audit = {
    "within24": {
        "samples": 0,
        "samples_with_labs": 0,
        "samples_with_potential_leakage": 0,
        "total_labs": 0,
        "potential_leaked_labs": 0,
    },
    "within48": {
        "samples": 0,
        "samples_with_labs": 0,
        "samples_with_potential_leakage": 0,
        "total_labs": 0,
        "potential_leaked_labs": 0,
    },
    "within_stay": {
        "samples": 0,
        "samples_with_labs": 0,
        "samples_with_potential_leakage": 0,
        "total_labs": 0,
        "potential_leaked_labs": 0,
    },
}


for i in tqdm(range(len(downstream_idx))):

    stay = downstream_idx[i]

    subject_id = stay['subject_id'][0]
    shard = stay['shard'][0]

    q_start_24 = stay['w24_start_1024'][0]
    q_end_24 = stay['w24_end_1024'][0]

    q_start_48 = stay['w48_start_1024'][0]
    q_end_48 = stay['w48_end_1024'][0]

    q_start_st = stay['wStay_start_1024'][0]
    q_end_st = stay['wStay_end_1024'][0]


    shard_df = pl.read_parquet(
        os.path.join(data_path, shard)
    )

    timeline = shard_df.filter(
        pl.col('subject_id') == subject_id
    )


    windows = {
        "within24": (q_start_24, q_end_24),
        "within48": (q_start_48, q_end_48),
        "within_stay": (q_start_st, q_end_st),
    }


    for name, (start, end) in windows.items():

        audit[name]["samples"] += 1

        query = timeline[start:end]

        labs = query.filter(
            pl.col("code").str.starts_with("LAB")
        )

        if labs.height == 0:
            continue

        audit[name]["samples_with_labs"] += 1
        audit[name]["total_labs"] += labs.height


        # last timestamp in query = prediction cutoff
        cutoff = query["time"].max()


        # labs occurring close to the cutoff
        potential = labs.filter(
            (
                cutoff - pl.col("time")
            ).dt.total_hours()
            <= delay_threshold_hours
        )


        n_potential = potential.height

        audit[name]["potential_leaked_labs"] += n_potential

        if n_potential > 0:
            audit[name]["samples_with_potential_leakage"] += 1



summary = []

for window, values in audit.items():

    summary.append({
        "window": window,
        "samples": values["samples"],
        "samples_with_labs": values["samples_with_labs"],
        "samples_with_potential_leakage": values["samples_with_potential_leakage"],
        "total_labs": values["total_labs"],
        "potential_leaked_labs": values["potential_leaked_labs"],
        "sample_leakage_rate": (
            values["samples_with_potential_leakage"]
            / values["samples"]
        ),
        "lab_leakage_rate": (
            values["potential_leaked_labs"]
            / values["total_labs"]
            if values["total_labs"] > 0 else 0
        ),
    })


audit_summary = pl.DataFrame(summary)

lab_audit_summary.write_parquet('lab_audit.parquet')

 16%|█▌        | 9594/61175 [26:34<2:22:52,  6.02it/s]

KeyboardInterrupt:

In [12]:
summary = []

for window, values in audit.items():

    summary.append({
        "window": window,
        "samples": values["samples"],
        "samples_with_labs": values["samples_with_labs"],
        "samples_with_potential_leakage": values["samples_with_potential_leakage"],
        "total_labs": values["total_labs"],
        "potential_leaked_labs": values["potential_leaked_labs"],
        "sample_leakage_rate": (
            values["samples_with_potential_leakage"]
            / values["samples"]
        ),
        "lab_leakage_rate": (
            values["potential_leaked_labs"]
            / values["total_labs"]
            if values["total_labs"] > 0 else 0
        ),
    })


audit_summary = pl.DataFrame(summary)

In [13]:
audit_summary

shape: (3, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ window     ┆ samples ┆ samples_wi ┆ samples_wi ┆ total_labs ┆ potential_ ┆ sample_le ┆ lab_leaka │
│ ---        ┆ ---     ┆ th_labs    ┆ th_potenti ┆ ---        ┆ leaked_lab ┆ akage_rat ┆ ge_rate   │
│ str        ┆ i64     ┆ ---        ┆ al_leakage ┆ i64        ┆ s          ┆ e         ┆ ---       │
│            ┆         ┆ i64        ┆ ---        ┆            ┆ ---        ┆ ---       ┆ f64       │
│            ┆         ┆            ┆ i64        ┆            ┆ i64        ┆ f64       ┆           │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ within24   ┆ 9594    ┆ 9269       ┆ 2734       ┆ 465581     ┆ 41943      ┆ 0.28497   ┆ 0.090087  │
│ within48   ┆ 9594    ┆ 9161       ┆ 2136       ┆ 391208     ┆ 29505      ┆ 0.222639  ┆ 0.07542   │
│ within_sta ┆ 9594    ┆ 8969       ┆ 1238       ┆ 346894     ┆ 13310      ┆ 0.129039  ┆ 0.038369  │
│ y          ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

In [15]:
pl.read_parquet('../audit_summary.parquet')

shape: (3, 5)
┌─────────────┬───────────────┬──────────────────────┬──────────────────────┬──────────────────────┐
│ window      ┆ total_queries ┆ queries_with_diagnos ┆ diagnosis_event_coun ┆ diagnosis_presence_r │
│ ---         ┆ ---           ┆ is                   ┆ t                    ┆ ate                  │
│ str         ┆ i64           ┆ ---                  ┆ ---                  ┆ ---                  │
│             ┆               ┆ i64                  ┆ i64                  ┆ f64                  │
╞═════════════╪═══════════════╪══════════════════════╪══════════════════════╪══════════════════════╡
│ within24    ┆ 61175         ┆ 186                  ┆ 2976                 ┆ 0.00304              │
│ within48    ┆ 61175         ┆ 3216                 ┆ 44476                ┆ 0.05257              │
│ within_stay ┆ 61175         ┆ 11128                ┆ 208692               ┆ 0.181904             │
└─────────────┴───────────────┴──────────────────────┴──────────────────────┴──────────────────────┘

In [98]:
rgp = pl.read_csv('./significance/ehrragp_y_los_7.csv')
rfrmr = pl.read_csv('./significance/vanilla_y_los_7.csv')

In [99]:
rgp.join(rfrmr, on=['icustay_id','label'], how='inner')

shape: (12_363, 4)
┌────────────┬───────┬────────────┬──────────────────┐
│ icustay_id ┆ label ┆ prediction ┆ prediction_right │
│ ---        ┆ ---   ┆ ---        ┆ ---              │
│ i64        ┆ f64   ┆ f64        ┆ f64              │
╞════════════╪═══════╪════════════╪══════════════════╡
│ 31205490   ┆ 0.0   ┆ 0.006104   ┆ 0.006104         │
│ 35044219   ┆ 0.0   ┆ 0.102539   ┆ 0.102539         │
│ 32773003   ┆ 1.0   ┆ 0.660156   ┆ 0.5078125        │
│ 37919158   ┆ 0.0   ┆ 0.318359   ┆ 0.214844         │
│ 38292466   ┆ 0.0   ┆ 0.425781   ┆ 0.322266         │
│ …          ┆ …     ┆ …          ┆ …                │
│ 30444664   ┆ 0.0   ┆ 0.042725   ┆ 0.022339         │
│ 36469520   ┆ 0.0   ┆ 0.005737   ┆ 0.005737         │
│ 30988867   ┆ 0.0   ┆ 0.84375    ┆ 0.722656         │
│ 37692584   ┆ 0.0   ┆ 0.120117   ┆ 0.108398         │
│ 35165301   ┆ 0.0   ┆ 0.152344   ┆ 0.151367         │
└────────────┴───────┴────────────┴──────────────────┘

In [100]:
threshold = 0.5

df = rgp.join(
    rfrmr,
    on=['icustay_id','label'],
    how='inner'
)

df = df.with_columns([
    (pl.col("prediction") >= threshold).cast(pl.Int8).alias("rgp_pred_class"),
    (pl.col("prediction_right") >= threshold).cast(pl.Int8).alias("baseline_pred_class"),
])

df = df.with_columns([
    (pl.col("rgp_pred_class") == pl.col("label")).alias("rgp_correct"),
    (pl.col("baseline_pred_class") == pl.col("label")).alias("baseline_correct"),
])

In [101]:
df.filter(
    (~pl.col("baseline_correct")) &
    (pl.col("rgp_correct"))
)

shape: (122, 8)
┌────────────┬───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ icustay_id ┆ label ┆ prediction ┆ prediction ┆ rgp_pred_c ┆ baseline_p ┆ rgp_correc ┆ baseline_c │
│ ---        ┆ ---   ┆ ---        ┆ _right     ┆ lass       ┆ red_class  ┆ t          ┆ orrect     │
│ i64        ┆ f64   ┆ f64        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆            ┆ f64        ┆ i8         ┆ i8         ┆ bool       ┆ bool       │
╞════════════╪═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 32743332   ┆ 1.0   ┆ 0.671875   ┆ 0.488281   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 39699336   ┆ 1.0   ┆ 0.609375   ┆ 0.484375   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 32631424   ┆ 0.0   ┆ 0.490234   ┆ 0.527344   ┆ 0          ┆ 1          ┆ true       ┆ false      │
│ 33674470   ┆ 1.0   ┆ 0.550781   ┆ 0.451172   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 34241430   ┆ 1.0   ┆ 0.605469   ┆ 0.470703   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 35278428   ┆ 1.0   ┆ 0.519531   ┆ 0.466797   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 30357604   ┆ 1.0   ┆ 0.515625   ┆ 0.3828125  ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 31991205   ┆ 1.0   ┆ 0.550781   ┆ 0.490234   ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 37626849   ┆ 1.0   ┆ 0.640625   ┆ 0.3828125  ┆ 1          ┆ 0          ┆ true       ┆ false      │
│ 34194602   ┆ 1.0   ┆ 0.628906   ┆ 0.4609375  ┆ 1          ┆ 0          ┆ true       ┆ false      │
└────────────┴───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [102]:
df.filter(
    (pl.col("baseline_correct")) &
    (~pl.col("rgp_correct"))
)

shape: (106, 8)
┌────────────┬───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ icustay_id ┆ label ┆ prediction ┆ prediction ┆ rgp_pred_c ┆ baseline_p ┆ rgp_correc ┆ baseline_c │
│ ---        ┆ ---   ┆ ---        ┆ _right     ┆ lass       ┆ red_class  ┆ t          ┆ orrect     │
│ i64        ┆ f64   ┆ f64        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆            ┆ f64        ┆ i8         ┆ i8         ┆ bool       ┆ bool       │
╞════════════╪═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 38740124   ┆ 0.0   ┆ 0.527344   ┆ 0.486328   ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 34146568   ┆ 1.0   ┆ 0.353516   ┆ 0.546875   ┆ 0          ┆ 1          ┆ false      ┆ true       │
│ 32751084   ┆ 0.0   ┆ 0.636719   ┆ 0.400391   ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 38603673   ┆ 0.0   ┆ 0.65625    ┆ 0.46875    ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 34996407   ┆ 0.0   ┆ 0.636719   ┆ 0.2734375  ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 35298179   ┆ 0.0   ┆ 0.636719   ┆ 0.4765625  ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 30852793   ┆ 0.0   ┆ 0.535156   ┆ 0.470703   ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 30316992   ┆ 0.0   ┆ 0.636719   ┆ 0.451172   ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 35371457   ┆ 0.0   ┆ 0.527344   ┆ 0.484375   ┆ 1          ┆ 0          ┆ false      ┆ true       │
│ 30172818   ┆ 0.0   ┆ 0.5546875  ┆ 0.449219   ┆ 1          ┆ 0          ┆ false      ┆ true       │
└────────────┴───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [103]:
df.filter(
    pl.col("baseline_correct") &
    pl.col("rgp_correct")
)

shape: (11_062, 8)
┌────────────┬───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ icustay_id ┆ label ┆ prediction ┆ prediction ┆ rgp_pred_c ┆ baseline_p ┆ rgp_correc ┆ baseline_c │
│ ---        ┆ ---   ┆ ---        ┆ _right     ┆ lass       ┆ red_class  ┆ t          ┆ orrect     │
│ i64        ┆ f64   ┆ f64        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆            ┆ f64        ┆ i8         ┆ i8         ┆ bool       ┆ bool       │
╞════════════╪═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 31205490   ┆ 0.0   ┆ 0.006104   ┆ 0.006104   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 35044219   ┆ 0.0   ┆ 0.102539   ┆ 0.102539   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 32773003   ┆ 1.0   ┆ 0.660156   ┆ 0.5078125  ┆ 1          ┆ 1          ┆ true       ┆ true       │
│ 37919158   ┆ 0.0   ┆ 0.318359   ┆ 0.214844   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 38292466   ┆ 0.0   ┆ 0.425781   ┆ 0.322266   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 34817232   ┆ 0.0   ┆ 0.017944   ┆ 0.012451   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 30444664   ┆ 0.0   ┆ 0.042725   ┆ 0.022339   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 36469520   ┆ 0.0   ┆ 0.005737   ┆ 0.005737   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 37692584   ┆ 0.0   ┆ 0.120117   ┆ 0.108398   ┆ 0          ┆ 0          ┆ true       ┆ true       │
│ 35165301   ┆ 0.0   ┆ 0.152344   ┆ 0.151367   ┆ 0          ┆ 0          ┆ true       ┆ true       │
└────────────┴───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [104]:
df.filter(
    (~pl.col("baseline_correct")) &
    (~pl.col("rgp_correct"))
)

shape: (1_073, 8)
┌────────────┬───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ icustay_id ┆ label ┆ prediction ┆ prediction ┆ rgp_pred_c ┆ baseline_p ┆ rgp_correc ┆ baseline_c │
│ ---        ┆ ---   ┆ ---        ┆ _right     ┆ lass       ┆ red_class  ┆ t          ┆ orrect     │
│ i64        ┆ f64   ┆ f64        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆            ┆ f64        ┆ i8         ┆ i8         ┆ bool       ┆ bool       │
╞════════════╪═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 39801884   ┆ 0.0   ┆ 0.816406   ┆ 0.691406   ┆ 1          ┆ 1          ┆ false      ┆ false      │
│ 31950308   ┆ 1.0   ┆ 0.194336   ┆ 0.161133   ┆ 0          ┆ 0          ┆ false      ┆ false      │
│ 37509585   ┆ 0.0   ┆ 0.890625   ┆ 0.894531   ┆ 1          ┆ 1          ┆ false      ┆ false      │
│ 37086676   ┆ 1.0   ┆ 0.3671875  ┆ 0.15918    ┆ 0          ┆ 0          ┆ false      ┆ false      │
│ 39061571   ┆ 0.0   ┆ 0.890625   ┆ 0.875      ┆ 1          ┆ 1          ┆ false      ┆ false      │
│ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 34132866   ┆ 1.0   ┆ 0.042725   ┆ 0.014038   ┆ 0          ┆ 0          ┆ false      ┆ false      │
│ 37049736   ┆ 1.0   ┆ 0.021606   ┆ 0.021606   ┆ 0          ┆ 0          ┆ false      ┆ false      │
│ 37029190   ┆ 0.0   ┆ 0.6953125  ┆ 0.675781   ┆ 1          ┆ 1          ┆ false      ┆ false      │
│ 34058245   ┆ 1.0   ┆ 0.46875    ┆ 0.292969   ┆ 0          ┆ 0          ┆ false      ┆ false      │
│ 30988867   ┆ 0.0   ┆ 0.84375    ┆ 0.722656   ┆ 1          ┆ 1          ┆ false      ┆ false      │
└────────────┴───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [105]:
df.select([
    pl.col("rgp_correct").sum().alias("EHR-RAGp correct"),
    pl.col("baseline_correct").sum().alias("Baseline correct"),
    ((~pl.col("baseline_correct")) & pl.col("rgp_correct")).sum().alias("Fixed by retrieval"),
    (pl.col("baseline_correct") & (~pl.col("rgp_correct"))).sum().alias("Broken by retrieval"),
])

shape: (1, 4)
┌──────────────────┬──────────────────┬────────────────────┬─────────────────────┐
│ EHR-RAGp correct ┆ Baseline correct ┆ Fixed by retrieval ┆ Broken by retrieval │
│ ---              ┆ ---              ┆ ---                ┆ ---                 │
│ u32              ┆ u32              ┆ u32                ┆ u32                 │
╞══════════════════╪══════════════════╪════════════════════╪═════════════════════╡
│ 11184            ┆ 11168            ┆ 122                ┆ 106                 │
└──────────────────┴──────────────────┴────────────────────┴─────────────────────┘

In [1]:
import polars as pl

In [63]:
can = pl.read_parquet('../candidates.parquet')

In [64]:
ragp = pl.read_csv('./significance/ehrragp_y_mort_1yr.csv')
# bsln = pl.read_csv('./significance/roformer_y_icu_readmit_30.csv')

In [65]:
# within24
# within48
# within_stay
ids = list(can.filter(pl.col('window') == 'within_stay')['icustay_id'].unique())

In [66]:
len(ids)

11128

In [67]:
df = ragp.filter(pl.col('icustay_id').is_in(ids) == False)

In [68]:
import torch
from torchmetrics.classification import BinaryAUROC, BinaryAveragePrecision


y_true = torch.tensor(df["label"].to_numpy()).long()
y_score = torch.tensor(df["prediction"].to_numpy()).float()


auroc_metric = BinaryAUROC()
auprc_metric = BinaryAveragePrecision()


auroc = auroc_metric(y_score, y_true)
auprc = auprc_metric(y_score, y_true)


print(f"AUROC: {auroc.item():.3f}")
print(f"AUPRC: {auprc.item():.3f}")

AUROC: 0.795
AUPRC: 0.354

In [69]:
can['window'].unique()

shape: (3,)
Series: 'window' [str]
[
	"within24"
	"within48"
	"within_stay"
]

In [ ]:
AUROC: 0.795
AUPRC: 0.354